/**
 * LabelForge Sample Data, Pre-built Industry Templates & Printer Profiles
 */

import { LabelDocument } from '../types/label';
import { DataSourceDefinition, SerializationCounter } from '../types/database';
import { PrinterProfile, PrintJob, PrintAuditLog, BarTenderTemplateMetadata } from '../types/printer';
import { AutomationWorkflow } from '../types/workflow';

export const INITIAL_COUNTER: SerializationCounter = {
  id: 'cnt-01',
  name: 'Production Pallet Serializer',
  currentValue: 4092,
  increment: 1,
  step: 1,
  padLength: 6,
  padding: 6,
  prefix: 'SN-',
  suffix: '',
  resetInterval: 'never',
};

export const SAMPLE_SERIAL_COUNTER: SerializationCounter = INITIAL_COUNTER;

export const SAMPLE_PRINTERS: PrinterProfile[] = [
  {
    id: 'prn-01',
    name: 'Zebra ZT410 Industrial (300 DPI)',
    displayName: 'Zebra ZT410 High-Speed Pallet Line 1',
    model: 'ZT410-300dpi',
    manufacturer: 'Zebra',
    location: 'Warehouse Dock Bay 4 - Line 1',
    connectionType: 'TCP/IP',
    systemPrinterName: '\\\\PRINTSVR01\\Zebra-ZT410-Bay4',
    dpi: 300,
    language: 'ZPL',
    connection: 'TCP/IP',
    address: '192.168.10.45:9100',
    status: 'Ready',
    isEnabled: true,
    isDefault: true,
    priority: 1,
    fallbackPrinterId: 'prn-03',
    supportedLabelSizes: ['4x6 in (100x150mm)', '4x4 in (100x100mm)', '4x2 in (100x50mm)'],
    supportedResolutions: [203, 300],
    supportedPrintTechnology: 'Thermal transfer',
    supportsCutter: true,
    supportsPeeler: true,
    supportsRfid: true,
    darkness: 18,
    speed: 8,
    mediaType: 'gap',
    lastSuccessfulPrintTime: '2026-09-18 03:45:12',
    lastKnownError: undefined,
    assignedTemplates: ['tpl-gs1-pallet', 'btw-asset-01', 'btw-wh-bin'],
    allowedRoles: ['SYSTEM_ADMIN', 'PRINT_MANAGER', 'OPERATOR'],
    notes: 'Primary logistics thermal transfer engine. Uses BarTender Enterprise Print Server Spooler.',
  },
  {
    id: 'prn-02',
    name: 'TSC TTP-244 Pro (203 DPI)',
    displayName: 'TSC TTP-244 Packing Bench 2',
    model: 'TTP-244 Pro',
    manufacturer: 'TSC',
    location: 'Packing Bench Station #2',
    connectionType: 'USB',
    systemPrinterName: 'TSC TTP-244 Pro (Direct USB)',
    dpi: 203,
    language: 'TSPL',
    connection: 'USB',
    address: 'USB002 (TSC Direct Spooler)',
    status: 'Ready',
    isEnabled: true,
    isDefault: false,
    priority: 2,
    fallbackPrinterId: 'prn-05',
    supportedLabelSizes: ['4x6 in (100x150mm)', '3x2 in (75x50mm)', '2.75x1.38 in (70x35mm)'],
    supportedResolutions: [203],
    supportedPrintTechnology: 'Direct thermal',
    supportsCutter: false,
    supportsPeeler: false,
    supportsRfid: false,
    darkness: 12,
    speed: 4,
    mediaType: 'black-mark',
    lastSuccessfulPrintTime: '2026-09-18 02:10:04',
    lastKnownError: undefined,
    assignedTemplates: ['tpl-pharma-vial', 'btw-retail-qr'],
    allowedRoles: ['SYSTEM_ADMIN', 'PRINT_MANAGER', 'OPERATOR'],
    notes: 'Fast on-demand direct thermal printer for dispatch benches.',
  },
  {
    id: 'prn-03',
    name: 'Brother TD-4550DNWB (300 DPI)',
    displayName: 'Brother TD-4550 Fallback Spooler',
    model: 'TD-4550DNWB',
    manufacturer: 'Brother',
    location: 'Warehouse Central Dispatch Office',
    connectionType: 'TCP/IP',
    systemPrinterName: '\\\\PRINTSVR01\\Brother-TD4550-Office',
    dpi: 300,
    language: 'ZPL',
    connection: 'TCP/IP',
    address: '192.168.10.82:9100',
    status: 'Ready',
    isEnabled: true,
    isDefault: false,
    priority: 3,
    fallbackPrinterId: 'prn-04',
    supportedLabelSizes: ['4x6 in (100x150mm)', '4x3 in (100x75mm)', '2.75x1.38 in (70x35mm)'],
    supportedResolutions: [300],
    supportedPrintTechnology: 'Direct thermal',
    supportsCutter: true,
    supportsPeeler: true,
    supportsRfid: false,
    darkness: 15,
    speed: 6,
    mediaType: 'gap',
    lastSuccessfulPrintTime: '2026-09-17 19:30:55',
    lastKnownError: undefined,
    assignedTemplates: ['tpl-gs1-pallet', 'tpl-pharma-vial'],
    allowedRoles: ['SYSTEM_ADMIN', 'PRINT_MANAGER'],
    notes: 'Designated automatic failover target when Zebra Line 1 reports cutter/ribbon errors.',
  },
  {
    id: 'prn-04',
    name: 'Windows Office Laser Spooler',
    displayName: 'HP Enterprise Laser M608 Sheet Spooler',
    model: 'HP LaserJet Enterprise M608',
    manufacturer: 'Generic Windows',
    location: 'Administrative Shipping Office Suite',
    connectionType: 'Windows Spooler',
    systemPrinterName: '\\\\PRINTSVR\\HP-WH-01',
    dpi: 600,
    language: 'Windows-GDI',
    connection: 'Windows Spooler',
    address: '\\\\PRINTSVR\\HP-WH-01',
    status: 'Ready',
    isEnabled: true,
    isDefault: false,
    priority: 4,
    fallbackPrinterId: undefined,
    supportedLabelSizes: ['Letter (8.5x11 in)', 'A4 (210x297mm) - Multi-Up Sheets'],
    supportedResolutions: [600],
    supportedPrintTechnology: 'Laser',
    supportsCutter: false,
    supportsPeeler: false,
    supportsRfid: false,
    darkness: 10,
    speed: 12,
    mediaType: 'continuous',
    lastSuccessfulPrintTime: '2026-09-18 01:22:19',
    lastKnownError: undefined,
    assignedTemplates: ['btw-asset-01'],
    allowedRoles: ['SYSTEM_ADMIN', 'PRINT_MANAGER', 'OPERATOR'],
    notes: 'Handles multi-up Avery adhesive sheet labels and packing documentation.',
  },
  {
    id: 'prn-05',
    name: 'Zebra LP 2844 Desktop (203 DPI)',
    displayName: 'Zebra LP 2844 Pharmacy Bench',
    model: 'LP 2844-Z',
    manufacturer: 'Zebra',
    location: 'Cleanroom Quarantine Lab',
    connectionType: 'USB',
    systemPrinterName: 'Zebra LP 2844 EPL Direct',
    dpi: 203,
    language: 'EPL',
    connection: 'USB',
    address: 'USB001 (Eltron EPL2)',
    status: 'Offline',
    isEnabled: false,
    isDefault: false,
    priority: 5,
    fallbackPrinterId: 'prn-02',
    supportedLabelSizes: ['2.75x1.38 in (70x35mm)', '2x1 in (50x25mm)'],
    supportedResolutions: [203],
    supportedPrintTechnology: 'Direct thermal',
    supportsCutter: false,
    supportsPeeler: false,
    supportsRfid: false,
    darkness: 10,
    speed: 3,
    mediaType: 'gap',
    lastSuccessfulPrintTime: '2026-09-16 14:02:40',
    lastKnownError: 'Printer offline — verify USB cable and power switch.',
    assignedTemplates: ['tpl-pharma-vial'],
    allowedRoles: ['SYSTEM_ADMIN'],
    notes: 'Currently undergoing scheduled preventive maintenance. Redirect to TSC Bench 2.',
  }
];

export const SAMPLE_BARTENDER_TEMPLATES: BarTenderTemplateMetadata[] = [
  {
    id: 'tpl-gs1-pallet',
    name: 'GS1 Standard Logistics Shipping Pallet Label',
    displayName: 'GS1-128 Global Logistics Pallet (100×150 mm)',
    category: 'Shipping label',
    bartenderTemplateReference: 'templates/logistics/GS1_Pallet_Shipping_v3.btw',
    templatePathReference: '/templates/logistics/GS1_Pallet_Shipping_v3.btw',
    labelWidth: 100,
    labelHeight: 150,
    unit: 'mm',
    barcodeType: 'GS1-128 / SSCC',
    supportsQr: true,
    supportsRfid: true,
    requiredFields: [
      { key: 'Customer_Name', label: 'Customer / Consignee', type: 'text', required: true, description: 'Receiving enterprise name' },
      { key: 'Destination_City', label: 'Destination City & Hub', type: 'text', required: true, description: 'Distribution airport or city' },
      { key: 'Product_Desc', label: 'Product Description', type: 'text', required: true, description: 'Line item trade description' },
      { key: 'Lot_Number', label: 'Batch / Lot Number', type: 'text', required: true, description: 'Production lot code' },
      { key: 'SSCC_Code', label: 'SSCC-18 Code', type: 'barcode', required: true, description: '18-digit Serial Shipping Container Code', validationRegex: '^[0-9]{18}$', errorMessage: 'Must be 18 digits' },
    ],
    optionalFields: [
      { key: 'Product_Tamil', label: 'Tamil Translation', type: 'text', required: false },
      { key: 'Product_Hindi', label: 'Hindi Translation', type: 'text', required: false },
      { key: 'Product_Arabic', label: 'Arabic Translation', type: 'text', required: false },
      { key: 'Tracking_No', label: 'Carrier Tracking Number', type: 'text', required: false },
      { key: 'Gross_Weight_Kg', label: 'Gross Weight (kg)', type: 'number', required: false },
    ],
    defaultPrinterId: 'prn-01',
    fallbackPrinterId: 'prn-03',
    isActive: true,
    notes: 'Standard GS1 compliant template. Integrated with BarTender Print Server via REST API.',
    createdAt: '2026-09-01 08:00:00',
    updatedAt: '2026-09-14 05:00:00',
  },
  {
    id: 'tpl-pharma-vial',
    name: 'Pharma DSCSA & EU FMD Vial Identifier',
    displayName: 'Pharma Vial 2D Serialization (70×35 mm)',
    category: 'Compliance label',
    bartenderTemplateReference: 'templates/healthcare/Pharma_Vial_Serial_v2.btw',
    templatePathReference: '/templates/healthcare/Pharma_Vial_Serial_v2.btw',
    labelWidth: 70,
    labelHeight: 35,
    unit: 'mm',
    barcodeType: 'GS1 DataMatrix (ECC 200)',
    supportsQr: false,
    supportsRfid: false,
    requiredFields: [
      { key: 'Drug_Name', label: 'Proprietary Drug Name', type: 'text', required: true, defaultValue: 'Remdesivir Injectable 100mg/vial' },
      { key: 'GTIN', label: 'GTIN-14 Product Code', type: 'barcode', required: true, defaultValue: '00300123456789', validationRegex: '^[0-9]{14}$', errorMessage: 'GTIN-14 must be 14 digits' },
      { key: 'EXP_Date', label: 'Expiry Date (YYYY-MM-DD)', type: 'date', required: true, defaultValue: '2028-12-31' },
      { key: 'LOT_Num', label: 'Lot / Batch ID', type: 'text', required: true, defaultValue: 'LOT-X994' },
      { key: 'SERIAL', label: 'Unit Serial Number', type: 'text', required: true, defaultValue: 'SN-004092' },
    ],
    optionalFields: [
      { key: 'NDC', label: 'National Drug Code', type: 'text', required: false },
      { key: 'Storage_Condition', label: 'Storage Temp Spec', type: 'text', required: false },
    ],
    defaultPrinterId: 'prn-01',
    fallbackPrinterId: 'prn-02',
    isActive: true,
    notes: 'Meets DSCSA Track & Trace mandate with ECC 200 square matrix symbol.',
    createdAt: '2026-09-05 10:30:00',
    updatedAt: '2026-09-14 05:00:00',
  },
  {
    id: 'btw-asset-01',
    name: 'Enterprise IT Asset & Equipment QR Tag',
    displayName: 'Fixed Asset Identification (100×50 mm)',
    category: 'Asset label',
    bartenderTemplateReference: 'templates/assets/IT_Equipment_Tag_v1.btw',
    templatePathReference: '/templates/assets/IT_Equipment_Tag_v1.btw',
    labelWidth: 100,
    labelHeight: 50,
    unit: 'mm',
    barcodeType: 'QR Code + Code 128',
    supportsQr: true,
    supportsRfid: true,
    requiredFields: [
      { key: 'Asset_ID', label: 'Asset Tag ID', type: 'text', required: true, defaultValue: 'AST-2026-0941' },
      { key: 'Asset_Name', label: 'Equipment Model', type: 'text', required: true, defaultValue: 'Dell PowerEdge R760 Rack Server' },
      { key: 'Department', label: 'Owning Business Unit', type: 'text', required: true, defaultValue: 'Global Infrastructure & Cloud Ops' },
      { key: 'Serial_Number', label: 'Manufacturer Serial No', type: 'text', required: true, defaultValue: 'SERV-8849-019' },
    ],
    optionalFields: [
      { key: 'Purchase_Date', label: 'Commission Date', type: 'date', required: false },
      { key: 'Location_Rack', label: 'Data Center Rack ID', type: 'text', required: false },
    ],
    defaultPrinterId: 'prn-01',
    fallbackPrinterId: 'prn-04',
    isActive: true,
    notes: 'Durable polyester substrate with thermal resin ribbon for longevity.',
    createdAt: '2026-09-10 11:15:00',
    updatedAt: '2026-09-15 14:20:00',
  },
  {
    id: 'btw-wh-bin',
    name: 'Warehouse High-Rack Storage Location Identifier',
    displayName: 'Rack Bin Location Sign (100×75 mm)',
    category: 'Warehouse label',
    bartenderTemplateReference: 'templates/warehouse/Rack_Bin_Location_v2.btw',
    templatePathReference: '/templates/warehouse/Rack_Bin_Location_v2.btw',

    labelWidth: 100,
    labelHeight: 75,
    unit: 'mm',
    barcodeType: 'Code 128 High-Density',
    supportsQr: true,
    supportsRfid: false,
    requiredFields: [
      { key: 'Zone', label: 'Facility Warehouse Zone', type: 'text', required: true, defaultValue: 'Zone B - Cold Storage' },
      { key: 'Aisle', label: 'Aisle Identifier', type: 'text', required: true, defaultValue: 'AISLE-14' },
      { key: 'Bin_Code', label: 'Full Location Code', type: 'barcode', required: true, defaultValue: 'B-14-04-A', validationRegex: '^[A-Z0-9-]+$', errorMessage: 'Alphanumeric and dashes only' },
    ],
    optionalFields: [
      { key: 'Max_Capacity', label: 'Max Pallet Capacity', type: 'number', required: false },
    ],
    defaultPrinterId: 'prn-01',
    fallbackPrinterId: 'prn-03',
    isActive: true,
    notes: 'High-contrast black on yellow retro-reflective media for long-range barcode scanners.',
    createdAt: '2026-09-12 09:00:00',
    updatedAt: '2026-09-16 16:45:00',
  }
];

export const SAMPLE_PRINT_JOBS: PrintJob[] = [
  {
    id: 'JOB-2026-881901',
    jobNumber: 'PJ-881901',
    jobType: 'ON_DEMAND',
    jobName: 'GS1 Pallet - Nordic Health Consignment #8849',
    requestedByUserId: 'usr-002',
    requestedByUserName: 'Elena Rostova',
    userRole: 'OPERATOR',
    templateId: 'tpl-gs1-pallet',
    templateName: 'GS1 Standard Logistics Shipping Pallet Label',
    templateVersion: 3,
    printerId: 'prn-01',
    printerName: 'Zebra ZT410 Industrial (300 DPI)',
    requestedPrinterId: 'prn-01',
    actualPrinterId: 'prn-01',
    actualPrinterName: 'Zebra ZT410 Industrial (300 DPI)',
    fallbackPrinterUsed: false,
    copies: 2,
    recordCount: 1,
    labelQuantity: 2,
    status: 'COMPLETED',
    createdAt: '2026-09-18 03:45:10',
    sentAt: '2026-09-18 03:45:11',
    completedAt: '2026-09-18 03:45:12',
    outputLanguage: 'ZPL',
    dpi: 300,
    paperSize: '100 × 150 mm (4.0" × 6.0")',
    inkLevel: 84,
    ribbonLevel: 84,
    mediaRollRemaining: 72,
    printheadHealth: 99,
    printSpeed: 6.0,
    darkness: 18,
    printTechnology: 'Thermal transfer',
    mediaType: 'gap',
    integrationMethod: 'BarTender REST API (v1/print)',
    integrationResponseSummary: 'HTTP 200 OK — Spooler Job ID #99812 confirmed by BarTender Print Server.',
    retryCount: 0,
    auditReference: 'AUD-901',
  },
  {
    id: 'JOB-2026-881902',
    jobNumber: 'PJ-881902',
    jobType: 'BATCH',
    jobName: 'Pharma DSCSA Batch Run LOT-X994',
    requestedByUserId: 'usr-001',
    requestedByUserName: 'Marcus Vance',
    userRole: 'PRINT_MANAGER',
    templateId: 'tpl-pharma-vial',
    templateName: 'Pharma DSCSA & EU FMD Vial Identifier',
    templateVersion: 2,
    printerId: 'prn-02',
    printerName: 'TSC TTP-244 Pro (203 DPI)',
    requestedPrinterId: 'prn-02',
    actualPrinterId: 'prn-02',
    actualPrinterName: 'TSC TTP-244 Pro (203 DPI)',
    fallbackPrinterUsed: false,
    copies: 50,
    recordCount: 50,
    labelQuantity: 50,
    status: 'COMPLETED',
    createdAt: '2026-09-18 02:10:00',
    sentAt: '2026-09-18 02:10:02',
    completedAt: '2026-09-18 02:10:04',
    outputLanguage: 'TSPL',
    dpi: 203,
    paperSize: '70 × 35 mm (2.75" × 1.38")',
    inkLevel: 68,
    ribbonLevel: 68,
    mediaRollRemaining: 88,
    printheadHealth: 97,
    printSpeed: 5.0,
    darkness: 15,
    printTechnology: 'Thermal transfer',
    mediaType: 'gap',
    integrationMethod: 'BarTender Direct Windows Driver Spooler',
    integrationResponseSummary: 'Job successfully spooled to TSPL driver queue. 50 labels confirmed.',
    retryCount: 0,
    auditReference: 'AUD-902',
  },
  {
    id: 'JOB-2026-881903',
    jobNumber: 'PJ-881903',
    jobType: 'ON_DEMAND',
    jobName: 'GS1 Pallet - Outbound Bay 4 Failover Test',
    requestedByUserId: 'usr-003',
    requestedByUserName: 'Devon Miller',
    userRole: 'SYSTEM_ADMIN',
    templateId: 'tpl-gs1-pallet',
    templateName: 'GS1 Standard Logistics Shipping Pallet Label',
    templateVersion: 3,
    printerId: 'prn-01',
    printerName: 'Zebra ZT410 Industrial (300 DPI)',
    requestedPrinterId: 'prn-01',
    actualPrinterId: 'prn-03',
    actualPrinterName: 'Brother TD-4550DNWB (Fallback)',
    fallbackPrinterId: 'prn-03',
    fallbackPrinterUsed: true,
    copies: 1,
    recordCount: 1,
    labelQuantity: 1,
    status: 'SENT_TO_PRINT_SERVICE',
    createdAt: '2026-09-18 01:55:20',
    sentAt: '2026-09-18 01:55:22',
    outputLanguage: 'ZPL',
    dpi: 300,
    paperSize: '100 × 150 mm (4.0" × 6.0")',
    inkLevel: 91,
    ribbonLevel: 91,
    mediaRollRemaining: 45,
    printheadHealth: 98,
    printSpeed: 6.0,
    darkness: 20,
    printTechnology: 'Direct thermal',
    mediaType: 'gap',
    integrationMethod: 'BarTender Automation Failover Handler',
    integrationResponseSummary: 'Primary printer busy; automatically routed to fallback Brother TD-4550DNWB (PRINT HANDOFF CONFIRMED).',
    retryCount: 1,
    auditReference: 'AUD-903',
  },
  {
    id: 'JOB-2026-881904',
    jobNumber: 'PJ-881904',
    jobType: 'TEST_PRINT',
    jobName: 'Diagnostic Calibration Test Print',
    requestedByUserId: 'usr-003',
    requestedByUserName: 'Devon Miller',
    userRole: 'SYSTEM_ADMIN',
    templateId: 'tpl-gs1-pallet',
    templateName: 'GS1 Standard Logistics Shipping Pallet Label',
    templateVersion: 3,
    printerId: 'prn-01',
    printerName: 'Zebra ZT410 Industrial (300 DPI)',
    requestedPrinterId: 'prn-01',
    actualPrinterId: 'prn-01',
    actualPrinterName: 'Zebra ZT410 Industrial (300 DPI)',
    fallbackPrinterUsed: false,
    copies: 1,
    recordCount: 1,
    labelQuantity: 1,
    status: 'COMPLETED',
    createdAt: '2026-09-18 01:15:00',
    sentAt: '2026-09-18 01:15:01',
    completedAt: '2026-09-18 01:15:02',
    outputLanguage: 'ZPL',
    dpi: 300,
    paperSize: '100 × 150 mm (4.0" × 6.0")',
    inkLevel: 79,
    ribbonLevel: 79,
    mediaRollRemaining: 60,
    printheadHealth: 100,
    printSpeed: 4.0,
    darkness: 16,
    printTechnology: 'Thermal transfer',
    mediaType: 'gap',
    integrationMethod: 'BarTender Test Print Diagnostic Routine',
    integrationResponseSummary: 'Darkness and pitch calibration pattern successfully transferred.',
    retryCount: 0,
    auditReference: 'AUD-904',
    priority: 'NORMAL',
  },
  {
    id: 'JOB-2026-881905',
    jobNumber: 'PJ-881905',
    jobType: 'BATCH',
    jobName: 'Outbound Warehouse Pallet Labels #9910',
    requestedByUserId: 'usr-002',
    requestedByUserName: 'Elena Rostova',
    userRole: 'OPERATOR',
    templateId: 'tpl-gs1-pallet',
    templateName: 'GS1 Standard Logistics Shipping Pallet Label',
    templateVersion: 3,
    printerId: 'prn-01',
    printerName: 'Zebra ZT410 Industrial (300 DPI)',
    requestedPrinterId: 'prn-01',
    actualPrinterId: 'prn-01',
    actualPrinterName: 'Zebra ZT410 Industrial (300 DPI)',
    fallbackPrinterUsed: false,
    copies: 12,
    recordCount: 12,
    labelQuantity: 12,
    status: 'QUEUED',
    priority: 'HIGH',
    queuePosition: 1,
    createdAt: '2026-09-22 04:30:00',
    sentAt: '2026-09-22 04:30:01',
    outputLanguage: 'ZPL',
    dpi: 300,
    paperSize: '100 × 150 mm (4.0" × 6.0")',
    inkLevel: 84,
    ribbonLevel: 84,
    mediaRollRemaining: 70,
    printheadHealth: 99,
    printSpeed: 6.0,
    darkness: 18,
    printTechnology: 'Thermal transfer',
    mediaType: 'gap',
    integrationMethod: 'BarTender REST API (v1/print)',
    integrationResponseSummary: 'Spooler Job ID #99830 in buffer queue; waiting for thermal head readiness.',
    retryCount: 0,
    auditReference: 'AUD-905',
  },
  {
    id: 'JOB-2026-881906',
    jobNumber: 'PJ-881906',
    jobType: 'ON_DEMAND',
    jobName: 'Urgent Stat Pharma Vial Serialization LOT-V202',
    requestedByUserId: 'usr-001',
    requestedByUserName: 'Marcus Vance',
    userRole: 'PRINT_MANAGER',
    templateId: 'tpl-pharma-vial',
    templateName: 'Pharma DSCSA & EU FMD Vial Identifier',
    templateVersion: 2,
    printerId: 'prn-02',
    printerName: 'TSC TTP-244 Pro (203 DPI)',
    requestedPrinterId: 'prn-02',
    actualPrinterId: 'prn-02',
    actualPrinterName: 'TSC TTP-244 Pro (203 DPI)',
    fallbackPrinterUsed: false,
    copies: 4,
    recordCount: 4,
    labelQuantity: 4,
    status: 'PRINTING',
    priority: 'URGENT',
    queuePosition: 2,
    createdAt: '2026-09-22 04:35:10',
    sentAt: '2026-09-22 04:35:11',
    outputLanguage: 'TSPL',
    dpi: 203,
    paperSize: '70 × 35 mm (2.75" × 1.38")',
    inkLevel: 68,
    ribbonLevel: 68,
    mediaRollRemaining: 88,
    printheadHealth: 97,
    printSpeed: 5.0,
    darkness: 15,
    printTechnology: 'Thermal transfer',
    mediaType: 'gap',
    integrationMethod: 'BarTender Direct Windows Driver Spooler',
    integrationResponseSummary: 'Active print stream in progress (2 of 4 labels fed through peeler).',
    retryCount: 0,
    auditReference: 'AUD-906',
  },
  {
    id: 'JOB-2026-881907',
    jobNumber: 'PJ-881907',
    jobType: 'BATCH',
    jobName: 'IT Asset Tagging Batch - North Wing Rack',
    requestedByUserId: 'usr-003',
    requestedByUserName: 'Devon Miller',
    userRole: 'SYSTEM_ADMIN',
    templateId: 'btw-asset-01',
    templateName: 'Enterprise IT Asset & Equipment QR Tag',
    templateVersion: 1,
    printerId: 'prn-01',
    printerName: 'Zebra ZT410 Industrial (300 DPI)',
    requestedPrinterId: 'prn-01',
    actualPrinterId: 'prn-01',
    actualPrinterName: 'Zebra ZT410 Industrial (300 DPI)',
    fallbackPrinterUsed: false,
    copies: 8,
    recordCount: 8,
    labelQuantity: 8,
    status: 'SENT_TO_PRINT_SERVICE',
    priority: 'NORMAL',
    queuePosition: 3,
    createdAt: '2026-09-22 04:38:00',
    sentAt: '2026-09-22 04:38:02',
    outputLanguage: 'ZPL',
    dpi: 300,
    paperSize: '100 × 50 mm',
    inkLevel: 84,
    ribbonLevel: 84,
    mediaRollRemaining: 70,
    printheadHealth: 99,
    printSpeed: 6.0,
    darkness: 18,
    printTechnology: 'Thermal transfer',
    mediaType: 'gap',
    integrationMethod: 'BarTender Automation Spooler',
    integrationResponseSummary: 'Job accepted by spooler service; queued for serialization.',
    retryCount: 0,
    auditReference: 'AUD-907',
  }
];

export const SAMPLE_AUDIT_LOGS: PrintAuditLog[] = [
  {
    id: 'AUD-901',
    timestamp: '2026-09-18 03:45:12',
    userId: 'usr-002',
    userName: 'Elena Rostova',
    userRole: 'OPERATOR',
    action: 'PRINT_JOB_REQUESTED',
    entityType: 'PrintJob',
    entityId: 'JOB-2026-881901',
    beforeValueJson: '{"status": "QUEUED"}',
    afterValueJson: '{"status": "COMPLETED", "printer": "prn-01", "copies": 2}',
    result: 'SUCCESS',
    ipAddress: '10.140.22.84',
  },
  {
    id: 'AUD-902',
    timestamp: '2026-09-18 02:10:04',
    userId: 'usr-001',
    userName: 'Marcus Vance',
    userRole: 'PRINT_MANAGER',
    action: 'PRINT_JOB_REQUESTED',
    entityType: 'PrintJob',
    entityId: 'JOB-2026-881902',
    beforeValueJson: '{"batch": "LOT-X994"}',
    afterValueJson: '{"status": "COMPLETED", "printer": "prn-02", "quantity": 50}',
    result: 'SUCCESS',
    ipAddress: '10.140.22.12',
  },
  {
    id: 'AUD-903',
    timestamp: '2026-09-18 01:55:22',
    userId: 'usr-003',
    userName: 'Devon Miller',
    userRole: 'SYSTEM_ADMIN',
    action: 'PRINTER_FALLBACK_USED',
    entityType: 'Printer',
    entityId: 'prn-01',
    beforeValueJson: '{"targetPrinter": "prn-01 (Zebra ZT410)"}',
    afterValueJson: '{"redirectedTo": "prn-03 (Brother TD-4550DNWB)", "reason": "Automatic failover policy"}',
    result: 'WARNING',
    ipAddress: '10.140.10.5',
  },
  {
    id: 'AUD-904',
    timestamp: '2026-09-18 01:15:02',
    userId: 'usr-003',
    userName: 'Devon Miller',
    userRole: 'SYSTEM_ADMIN',
    action: 'TEST_PRINT_DISPATCHED',
    entityType: 'Printer',
    entityId: 'prn-01',
    beforeValueJson: '{"testType": "diagnostic"}',
    afterValueJson: '{"status": "COMPLETED", "target": "prn-01"}',
    result: 'SUCCESS',
    ipAddress: '10.140.10.5',
  },
  {
    id: 'AUD-905',
    timestamp: '2026-09-17 16:30:00',
    userId: 'usr-003',
    userName: 'Devon Miller',
    userRole: 'SYSTEM_ADMIN',
    action: 'DEFAULT_PRINTER_CHANGED',
    entityType: 'Printer',
    entityId: 'prn-01',
    beforeValueJson: '{"defaultPrinter": "prn-02"}',
    afterValueJson: '{"defaultPrinter": "prn-01"}',
    result: 'SUCCESS',
    ipAddress: '10.140.10.5',
  }
];


export const SAMPLE_DATA_SOURCES: DataSourceDefinition[] = [
  {
    id: 'ds-logistics',
    name: 'Global Logistics Shipments DB',
    type: 'sql',
    description: 'PostgreSQL live feed for warehouse pick, pack and international shipping consignments.',
    connected: true,
    currentRecordIndex: 0,
    queryOrFilter: 'SELECT * FROM shipments WHERE status = "READY_TO_SHIP" ORDER BY priority DESC LIMIT 50;',
    fields: [
      { name: 'Consignment_ID', type: 'string', sampleValue: 'CN-8849102' },
      { name: 'Customer_Name', type: 'string', sampleValue: 'Apex Medical Supplies Ltd.' },
      { name: 'Destination_City', type: 'string', sampleValue: 'Frankfurt Airport Hub' },
      { name: 'Country_Code', type: 'string', sampleValue: 'DE' },
      { name: 'Product_Desc', type: 'string', sampleValue: 'High Precision Pipettes 100ul' },
      { name: 'Product_Tamil', type: 'string', sampleValue: 'துல்லிய மருத்துவக் குழாய்கள்' },
      { name: 'Product_Hindi', type: 'string', sampleValue: 'सटीक पिपेट उपकरण' },
      { name: 'Product_Arabic', type: 'string', sampleValue: 'أنابيب مدرجة عالية الدقة' },
      { name: 'Gross_Weight_Kg', type: 'string', sampleValue: '14.85' },
      { name: 'Package_Qty', type: 'string', sampleValue: '250' },
      { name: 'Lot_Number', type: 'string', sampleValue: 'LOT-2026-F44' },
      { name: 'SSCC_Code', type: 'string', sampleValue: '003061414112345678' },
      { name: 'GTIN_14', type: 'string', sampleValue: '10061414199993' },
      { name: 'Carrier', type: 'string', sampleValue: 'DHL Global Express' },
      { name: 'Tracking_No', type: 'string', sampleValue: 'JJD01928472910' }
    ],
    records: [
      {
        id: 1,
        Consignment_ID: 'CN-8849102',
        Customer_Name: 'Apex Medical Supplies Ltd.',
        Destination_City: 'Frankfurt Airport Hub',
        Country_Code: 'DE',
        Product_Desc: 'High Precision Pipettes 100ul',
        Product_Tamil: 'துல்லிய மருத்துவக் குழாய்கள்',
        Product_Hindi: 'सटीक पिपेट उपकरण',
        Product_Arabic: 'أنابيب مدرجة عالية الدقة',
        Gross_Weight_Kg: '14.85',
        Package_Qty: '250',
        Lot_Number: 'LOT-2026-F44',
        SSCC_Code: '003061414112345678',
        GTIN_14: '10061414199993',
        Carrier: 'DHL Global Express',
        Tracking_No: 'JJD01928472910'
      },
      {
        id: 2,
        Consignment_ID: 'CN-8849103',
        Customer_Name: 'Kyoto Biopharma Logistics',
        Destination_City: 'Kansai Int Distribution Ctr',
        Country_Code: 'JP',
        Product_Desc: 'Sterile Culture Flasks 250ml',
        Product_Tamil: 'மலட்டு கலாச்சார குப்பிகள்',
        Product_Hindi: 'बाँझ संस्कृति फ्लास्क',
        Product_Arabic: 'قوارير زراعة معقمة',
        Gross_Weight_Kg: '22.10',
        Package_Qty: '400',
        Lot_Number: 'LOT-2026-K92',
        SSCC_Code: '003061414198765432',
        GTIN_14: '10061414188882',
        Carrier: 'FedEx International',
        Tracking_No: '782910384912'
      },
      {
        id: 3,
        Consignment_ID: 'CN-8849104',
        Customer_Name: 'Nordic Health Systems',
        Destination_City: 'Stockholm Arlanda Gateway',
        Country_Code: 'SE',
        Product_Desc: 'Polymer Cryogenic Vials 2.0ml',
        Product_Tamil: 'குளிர்பதன பிளாஸ்டிக் பாட்டில்கள்',
        Product_Hindi: 'क्रायोजेनिक वायल 2ml',
        Product_Arabic: 'أوعية التبريد العميق',
        Gross_Weight_Kg: '8.40',
        Package_Qty: '1000',
        Lot_Number: 'LOT-2026-N11',
        SSCC_Code: '003061414133445566',
        GTIN_14: '10061414177771',
        Carrier: 'UPS Worldwide Saver',
        Tracking_No: '1Z9999999999999999'
      }
    ]
  }
];

export const TEMPLATES: LabelDocument[] = [
  // 1. GS1 Logistics Shipping Pallet Label (100mm x 150mm)
  {
    id: 'tpl-gs1-pallet',
    schemaVersion: '1.0.0',
    name: 'GS1 Standard Logistics Shipping Pallet Label',
    description: 'Compliant with GS1 General Specifications for multi-carrier global pallet identification.',
    author: 'Principal Architect',
    created: '2026-09-14T05:00:00Z',
    modified: '2026-09-14T05:00:00Z',
    dimensions: {
      width: 100,
      height: 150,
      unit: 'mm',
      dpi: 300,
      orientation: 'portrait',
      marginLeft: 2,
      marginTop: 2,
      marginRight: 2,
      marginBottom: 2,
      cornerRadius: 1,
    },
    metadata: {
      targetPrinter: 'prn-01',
      site: 'Global HQ Distribution Center',
      version: 3,
      status: 'approved',
    },
    objects: [
      // Header Section
      {
        id: 'obj-hdr-box',
        name: 'Shipment Header Box',
        type: 'rect',
        x: 3,
        y: 3,
        width: 94,
        height: 28,
        rotation: 0,
        locked: false,
        visible: true,
        opacity: 1,
        zIndex: 1,
        shapeStyle: {
          fillColor: 'transparent',
          strokeColor: '#000000',
          strokeWidth: 0.5,
        }
      },
      {
        id: 'obj-from-lbl',
        name: 'From Company Label',
        type: 'text',
        x: 5,
        y: 4,
        width: 45,
        height: 4,
        rotation: 0,
        locked: false,
        visible: true,
        opacity: 1,
        zIndex: 2,
        text: 'FROM: LABELFORGE GLOBAL LOGISTICS',
        style: {
          fontFamily: 'Segoe UI',
          fontSize: 7,
          fontWeight: 'bold',
          fontStyle: 'normal',
          underline: false,
          strikeout: false,
          color: '#000000',
          alignment: 'left',
          direction: 'ltr',
          lineHeight: 1.2,
          letterSpacing: 0,
          wrap: false,
        }
      },
      {
        id: 'obj-to-lbl',
        name: 'Ship To Customer Title',
        type: 'text',
        x: 5,
        y: 9,
        width: 45,
        height: 5,
        rotation: 0,
        locked: false,
        visible: true,
        opacity: 1,
        zIndex: 3,
        text: 'SHIP TO: {{Customer_Name}}',
        style: {
          fontFamily: 'Segoe UI',
          fontSize: 10,
          fontWeight: 'bold',
          fontStyle: 'normal',
          underline: false,
          strikeout: false,
          color: '#000000',
          alignment: 'left',
          direction: 'ltr',
          lineHeight: 1.2,
          letterSpacing: 0,
          wrap: false,
        }
      },
      {
        id: 'obj-dest-city',
        name: 'Destination City',
        type: 'text',
        x: 5,
        y: 15,
        width: 55,
        height: 7,
        rotation: 0,
        locked: false,
        visible: true,
        opacity: 1,
        zIndex: 4,
        text: '{{Destination_City}} [{{Country_Code}}]',
        style: {
          fontFamily: 'Segoe UI',
          fontSize: 12,
          fontWeight: 'bold',
          fontStyle: 'normal',
          underline: false,
          strikeout: false,
          color: '#000000',
          alignment: 'left',
          direction: 'ltr',
          lineHeight: 1.2,
          letterSpacing: 0,
          wrap: false,
        }
      },
      {
        id: 'obj-carrier-code',
        name: 'Carrier Code Badge',
        type: 'text',
        x: 65,
        y: 5,
        width: 30,
        height: 12,
        rotation: 0,
        locked: false,
        visible: true,
        opacity: 1,
        zIndex: 5,
        text: '{{Carrier}}\nPRIORITY 1',
        style: {
          fontFamily: 'IBM Plex Mono',
          fontSize: 9,
          fontWeight: 'bold',
          fontStyle: 'normal',
          underline: false,
          strikeout: false,
          color: '#000000',
          alignment: 'right',
          direction: 'ltr',
          lineHeight: 1.3,
          letterSpacing: 0,
          wrap: false,
        }
      },
      // Middle Section - Multilingual Product Details
      {
        id: 'obj-prod-box',
        name: 'Product Details Outer Box',
        type: 'rect',
        x: 3,
        y: 33,
        width: 94,
        height: 48,
        rotation: 0,
        locked: false,
        visible: true,
        opacity: 1,
        zIndex: 6,
        shapeStyle: {
          fillColor: 'transparent',
          strokeColor: '#000000',
          strokeWidth: 0.5,
        }
      },
      {
        id: 'obj-prod-en',
        name: 'English Product Description',
        type: 'text',
        x: 5,
        y: 35,
        width: 88,
        height: 6,
        rotation: 0,
        locked: false,
        visible: true,
        opacity: 1,
        zIndex: 7,
        text: 'ITEM: {{Product_Desc}}',
        style: {
          fontFamily: 'Segoe UI',
          fontSize: 11,
          fontWeight: 'bold',
          fontStyle: 'normal',
          underline: false,
          strikeout: false,
          color: '#000000',
          alignment: 'left',
          direction: 'ltr',
          lineHeight: 1.2,
          letterSpacing: 0,
          wrap: false,
        }
      },
      // Multilingual Indic and Arabic script demonstration
      {
        id: 'obj-prod-ta',
        name: 'Tamil Description (தமிழ்)',
        type: 'text',
        x: 5,
        y: 42,
        width: 88,
        height: 6,
        rotation: 0,
        locked: false,
        visible: true,
        opacity: 1,
        zIndex: 8,
        text: 'தமிழ்: {{Product_Tamil}}',
        style: {
          fontFamily: 'Noto Sans Tamil',
          fontSize: 10,
          fontWeight: 'normal',
          fontStyle: 'normal',
          underline: false,
          strikeout: false,
          color: '#000000',
          alignment: 'left',
          direction: 'ltr',
          lineHeight: 1.2,
          letterSpacing: 0,
          wrap: false,
        }
      },
      {
        id: 'obj-prod-hi',
        name: 'Hindi Description (हिन्दी)',
        type: 'text',
        x: 5,
        y: 49,
        width: 88,
        height: 6,
        rotation: 0,
        locked: false,
        visible: true,
        opacity: 1,
        zIndex: 9,
        text: 'हिन्दी: {{Product_Hindi}}',
        style: {
          fontFamily: 'Noto Sans Devanagari',
          fontSize: 10,
          fontWeight: 'normal',
          fontStyle: 'normal',
          underline: false,
          strikeout: false,
          color: '#000000',
          alignment: 'left',
          direction: 'ltr',
          lineHeight: 1.2,
          letterSpacing: 0,
          wrap: false,
        }
      },
      {
        id: 'obj-prod-ar',
        name: 'Arabic Description (العربية)',
        type: 'text',
        x: 5,
        y: 56,
        width: 88,
        height: 6,
        rotation: 0,
        locked: false,
        visible: true,
        opacity: 1,
        zIndex: 10,
        text: 'العربية: {{Product_Arabic}}',
        style: {
          fontFamily: 'Noto Sans Arabic',
          fontSize: 10,
          fontWeight: 'normal',
          fontStyle: 'normal',
          underline: false,
          strikeout: false,
          color: '#000000',
          alignment: 'right',
          direction: 'rtl',
          lineHeight: 1.2,
          letterSpacing: 0,
          wrap: false,
        }
      },
      {
        id: 'obj-lot-qty',
        name: 'Lot & Serial Row',
        type: 'text',
        x: 5,
        y: 65,
        width: 88,
        height: 10,
        rotation: 0,
        locked: false,
        visible: true,
        opacity: 1,
        zIndex: 11,
        text: 'LOT: {{Lot_Number}}   QTY: {{Package_Qty}} EA   WT: {{Gross_Weight_Kg}} KG   SERIAL: {{SERIAL}}',
        style: {
          fontFamily: 'IBM Plex Mono',
          fontSize: 8.5,
          fontWeight: '600',
          fontStyle: 'normal',
          underline: false,
          strikeout: false,
          color: '#000000',
          alignment: 'left',
          direction: 'ltr',
          lineHeight: 1.2,
          letterSpacing: 0,
          wrap: false,
        }
      },
      // 2D QR Code & Tracking Info
      {
        id: 'obj-qr-tracking',
        name: 'Consignment QR Verification',
        type: 'qrcode',
        x: 6,
        y: 84,
        width: 24,
        height: 24,
        rotation: 0,
        locked: false,
        visible: true,
        opacity: 1,
        zIndex: 12,
        value: 'https://verify.labelforge.io/consignment/{{Consignment_ID}}?lot={{Lot_Number}}&serial={{SERIAL}}',
        barcodeStyle: {
          symbology: 'qr',
          humanReadable: false,
          humanReadableFont: 'monospace',
          humanReadableSize: 8,
          humanReadablePosition: 'none',
          moduleWidth: 0.38,
          quietZone: true,
          quietZoneSize: 2,
          errorCorrectionLevel: 'M',
          color: '#000000',
          backgroundColor: 'transparent'
        }
      },
      // 1D Intermediate GS1-128
      {
        id: 'obj-gs1-gtin-barcode',
        name: 'GS1-128 Content Barcode',
        type: 'barcode',
        x: 33,
        y: 84,
        width: 63,
        height: 24,
        rotation: 0,
        locked: false,
        visible: true,
        opacity: 1,
        zIndex: 13,
        value: '(01)10061414199993(10)LOT-2026-F44(17)280630',
        barcodeStyle: {
          symbology: 'gs1-128',
          humanReadable: true,
          humanReadableFont: 'monospace',
          humanReadableSize: 8,
          humanReadablePosition: 'bottom',
          moduleWidth: 0.33,
          quietZone: true,
          quietZoneSize: 3,
          color: '#000000',
          backgroundColor: 'transparent'
        }
      },
      // Bottom Main SSCC (Serial Shipping Container Code) - Required for GS1 Pallet
      {
        id: 'obj-sscc-title',
        name: 'SSCC Title Text',
        type: 'text',
        x: 5,
        y: 112,
        width: 90,
        height: 5,
        rotation: 0,
        locked: false,
        visible: true,
        opacity: 1,
        zIndex: 14,
        text: 'SSCC (SERIAL SHIPPING CONTAINER CODE):',
        style: {
          fontFamily: 'Segoe UI',
          fontSize: 8.5,
          fontWeight: 'bold',
          fontStyle: 'normal',
          underline: false,
          strikeout: false,
          color: '#000000',
          alignment: 'center',
          direction: 'ltr',
          lineHeight: 1.2,
          letterSpacing: 0,
          wrap: false,
        }
      },
      {
        id: 'obj-sscc-barcode',
        name: 'Master SSCC-18 Barcode',
        type: 'barcode',
        x: 6,
        y: 118,
        width: 88,
        height: 28,
        rotation: 0,
        locked: false,
        visible: true,
        opacity: 1,
        zIndex: 15,
        value: '(00)306141411234567890',
        barcodeStyle: {
          symbology: 'gs1-128',
          humanReadable: true,
          humanReadableFont: 'monospace',
          humanReadableSize: 9,
          humanReadablePosition: 'bottom',
          moduleWidth: 0.495,
          quietZone: true,
          quietZoneSize: 4,
          color: '#000000',
          backgroundColor: 'transparent'
        }
      }
    ]
  },

  // 2. Pharma Compliance Vial Label (70mm x 35mm)
  {
    id: 'tpl-pharma-vial',
    schemaVersion: '1.0.0',
    name: 'Pharma DSCSA & EU FMD Vial Identifier',
    description: 'Unit dose serialization with GS1 DataMatrix ECC 200, GTIN, Expiry, Lot and Serial Number.',
    author: 'Principal Architect',
    created: '2026-09-14T05:00:00Z',
    modified: '2026-09-14T05:00:00Z',
    dimensions: {
      width: 70,
      height: 35,
      unit: 'mm',
      dpi: 300,
      orientation: 'landscape',
      marginLeft: 1.5,
      marginTop: 1.5,
      marginRight: 1.5,
      marginBottom: 1.5,
      cornerRadius: 1,
    },
    metadata: {
      targetPrinter: 'prn-01',
      site: 'Cleanroom Packaging Suite B',
      version: 2,
      status: 'approved',
    },
    objects: [
      {
        id: 'pharma-dm',
        name: 'GS1 DataMatrix (2D Serialization)',
        type: 'datamatrix',
        x: 3,
        y: 4,
        width: 25,
        height: 25,
        rotation: 0,
        locked: false,
        visible: true,
        opacity: 1,
        zIndex: 1,
        value: '(01)00300123456789(17)281231(10)LOT-X994(21){{SERIAL}}',
        barcodeStyle: {
          symbology: 'gs1-datamatrix',
          humanReadable: false,
          humanReadableFont: 'monospace',
          humanReadableSize: 7,
          humanReadablePosition: 'none',
          moduleWidth: 0.25,
          quietZone: true,
          quietZoneSize: 1,
          color: '#000000',
          backgroundColor: 'transparent'
        }
      },
      {
        id: 'pharma-name-en',
        name: 'Drug Name Proprietary',
        type: 'text',
        x: 30,
        y: 3,
        width: 38,
        height: 6,
        rotation: 0,
        locked: false,
        visible: true,
        opacity: 1,
        zIndex: 2,
        text: 'Remdesivir Injectable 100mg/vial',
        style: {
          fontFamily: 'Segoe UI',
          fontSize: 9,
          fontWeight: 'bold',
          fontStyle: 'normal',
          underline: false,
          strikeout: false,
          color: '#000000',
          alignment: 'left',
          direction: 'ltr',
          lineHeight: 1.2,
          letterSpacing: 0,
          wrap: true,
        }
      },
      {
        id: 'pharma-multilingual',
        name: 'Multilingual Warning (Tamil/Hindi)',
        type: 'text',
        x: 30,
        y: 10,
        width: 38,
        height: 5,
        rotation: 0,
        locked: false,
        visible: true,
        opacity: 1,
        zIndex: 3,
        text: 'மருத்துவ பயன்பாட்டிற்கு மட்டும் | केवल Rx',
        style: {
          fontFamily: 'Noto Sans Tamil',
          fontSize: 7.5,
          fontWeight: 'normal',
          fontStyle: 'normal',
          underline: false,
          strikeout: false,
          color: '#1a56db',
          alignment: 'left',
          direction: 'ltr',
          lineHeight: 1.2,
          letterSpacing: 0,
          wrap: false,
        }
      },
      {
        id: 'pharma-data-list',
        name: 'Human Readable AIs',
        type: 'text',
        x: 30,
        y: 16,
        width: 38,
        height: 16,
        rotation: 0,
        locked: false,
        visible: true,
        opacity: 1,
        zIndex: 4,
        text: 'GTIN: 00300123456789\nEXP:  2028-12-31\nLOT:  LOT-X994\nSN:   {{SERIAL}}',
        style: {
          fontFamily: 'IBM Plex Mono',
          fontSize: 7,
          fontWeight: '600',
          fontStyle: 'normal',
          underline: false,
          strikeout: false,
          color: '#000000',
          alignment: 'left',
          direction: 'ltr',
          lineHeight: 1.35,
          letterSpacing: 0,
          wrap: false,
        }
      }
    ]
  }
];

export const SAMPLE_TEMPLATES: LabelDocument[] = TEMPLATES;

export const SAMPLE_WORKFLOWS: AutomationWorkflow[] = [
  {
    id: 'wf-csv-spooler',
    name: 'Inbound CSV Drop & Auto-Spooler',
    description: 'Watches /var/spool/labelforge for ERP drop files, evaluates preflight, and sends ZPL directly to Zebra ZT410.',
    active: true,
    triggerType: 'file-drop',
    executionCount: 142,
    lastExecuted: '2026-09-14 05:01:22',
    lastStatus: 'success',
    nodes: [
      { id: 'n1', type: 'file-drop', title: 'File Drop Watcher (*.csv)', category: 'trigger', config: { path: '/spool/inbox/*.csv', intervalSec: 5 }, enabled: true, status: 'idle' },
      { id: 'n2', type: 'parse-csv', title: 'CSV Schema & Field Mapper', category: 'transform', config: { delimiter: ',', trim: true }, enabled: true, status: 'idle' },
      { id: 'n3', type: 'preflight-check', title: 'Enterprise Preflight Check', category: 'transform', config: { haltOnError: true }, enabled: true, status: 'idle' },
      { id: 'n4', type: 'assign-printer', title: 'Route to Zebra ZT410 (300 DPI)', category: 'print', config: { printerId: 'prn-01' }, enabled: true, status: 'idle' },
      { id: 'n5', type: 'execute-print', title: 'Direct Socket Print (Port 9100)', category: 'print', config: { format: 'ZPL', verifyCompletion: true }, enabled: true, status: 'idle' },
      { id: 'n6', type: 'archive-payload', title: 'Archive to /spool/processed', category: 'post-process', config: { retentionDays: 90 }, enabled: true, status: 'idle' }
    ]
  },
  {
    id: 'wf-rest-webhook',
    name: 'SAP / NetSuite Real-time Print Webhook',
    description: 'REST API listener on /api/v1/jobs for on-demand packing bench label generation.',
    active: true,
    triggerType: 'webhook',
    executionCount: 529,
    lastExecuted: '2026-09-14 04:58:10',
    lastStatus: 'success',
    nodes: [
      { id: 'w1', type: 'webhook', title: 'POST /api/v1/jobs Webhook', category: 'trigger', config: { auth: 'Bearer Token', rateLimit: 100 }, enabled: true, status: 'idle' },
      { id: 'w2', type: 'validate-data', title: 'JSON Schema Validation', category: 'transform', config: { strict: true }, enabled: true, status: 'idle' },
      { id: 'w3', type: 'execute-print', title: 'Send to TSC TTP-244 (TSPL)', category: 'print', config: { printerId: 'prn-02' }, enabled: true, status: 'idle' },
      { id: 'w4', type: 'send-webhook', title: 'POST Callback to ERP', category: 'post-process', config: { url: 'https://erp.example.com/events/printed' }, enabled: true, status: 'idle' }
    ]
  }
];

export const SAMPLE_WORKFLOW: AutomationWorkflow = SAMPLE_WORKFLOWS[0];

export interface MultilingualFontSpec {
  family: string;
  displayName: string;
  category: string;
  direction?: 'ltr' | 'rtl';
  sampleText: string;
}

export const MULTILINGUAL_FONTS: MultilingualFontSpec[] = [
  {
    family: 'Segoe UI',
    displayName: 'Segoe UI (Standard Latin & Industrial)',
    category: 'sans-serif',
    direction: 'ltr',
    sampleText: 'BARCODE & THERMAL SPECIFICATION TEST 123456',
  },
  {
    family: 'IBM Plex Mono',
    displayName: 'IBM Plex Mono (Monospace Logistics)',
    category: 'monospace',
    direction: 'ltr',
    sampleText: 'GTIN: (01)00614141999996 LOT: LOT-2026-X',
  },
  {
    family: 'Noto Sans Tamil',
    displayName: 'Noto Sans Tamil (தமிழ் - South India / Sri Lanka / Singapore)',
    category: 'indic',
    direction: 'ltr',
    sampleText: 'மருத்துவ தயாரிப்பு விவரக்குறிப்பு - தொகுதி எண்: 98842',
  },
  {
    family: 'Noto Sans Devanagari',
    displayName: 'Noto Sans Devanagari (हिन्दी - India & Nepal)',
    category: 'indic',
    direction: 'ltr',
    sampleText: 'गुणवत्ता आश्वासन एवं औद्योगिक मुद्रण प्रणाली',
  },
  {
    family: 'Noto Sans Arabic',
    displayName: 'Noto Sans Arabic (العربية - Middle East / North Africa RTL)',
    category: 'arabic',
    direction: 'rtl',
    sampleText: 'مستودع التوزيع الدولي - شحنة رقمية معتمدة',
  },
  {
    family: 'Noto Sans SC',
    displayName: 'Noto Sans SC (简体中文 - Simplified Chinese)',
    category: 'cjk',
    direction: 'ltr',
    sampleText: '企业级热敏标签设计与工业级打印系统',
  },
  {
    family: 'Noto Sans JP',
    displayName: 'Noto Sans JP (日本語 - Japanese)',
    category: 'cjk',
    direction: 'ltr',
    sampleText: '高精度サーマルプリンター制御およびバーコード検証',
  },
];

