/**
 * LabelForge Sample Data, Pre-built Industry Templates & Printer Profiles
 */

import { LabelDocument } from '../types/label';
import { DataSourceDefinition, SerializationCounter } from '../types/database';
import { PrinterProfile } from '../types/printer';
import { AutomationWorkflow } from '../types/workflow';

export const INITIAL_COUNTER: SerializationCounter = {
  id: 'cnt-01',
  name: 'Production Pallet Serializer',
  currentValue: 4092,
  increment: 1,
  step: 1,
  padLength: 6,
  padding: 6,
  prefix: 'SN-',
  suffix: '',
  resetInterval: 'never',
};

export const SAMPLE_SERIAL_COUNTER: SerializationCounter = INITIAL_COUNTER;

export const SAMPLE_PRINTERS: PrinterProfile[] = [
  {
    id: 'prn-01',
    name: 'Zebra ZT410 Industrial (300 DPI)',
    model: 'ZT410-300dpi',
    manufacturer: 'Zebra',
    dpi: 300,
    language: 'ZPL',
    connection: 'TCP/IP',
    address: '192.168.10.45:9100',
    status: 'Ready',
    supportsCutter: true,
    supportsPeeler: true,
    supportsRfid: true,
    darkness: 18,
    speed: 6,
    mediaType: 'gap',
  },
  {
    id: 'prn-02',
    name: 'TSC TTP-244 Pro (203 DPI)',
    model: 'TTP-244 Pro',
    manufacturer: 'TSC',
    dpi: 203,
    language: 'TSPL',
    connection: 'USB',
    address: 'USB002 (TSC Direct)',
    status: 'Ready',
    supportsCutter: false,
    supportsPeeler: false,
    supportsRfid: false,
    darkness: 12,
    speed: 4,
    mediaType: 'black-mark',
  },
  {
    id: 'prn-03',
    name: 'Brother TD-4550DNWB (300 DPI)',
    model: 'TD-4550DNWB',
    manufacturer: 'Brother',
    dpi: 300,
    language: 'ZPL',
    connection: 'TCP/IP',
    address: '192.168.10.82:9100',
    status: 'Ready',
    supportsCutter: true,
    supportsPeeler: true,
    supportsRfid: false,
    darkness: 15,
    speed: 6,
    mediaType: 'gap',
  },
  {
    id: 'prn-04',
    name: 'Windows Office Laser Spooler',
    model: 'HP LaserJet Enterprise M608',
    manufacturer: 'Generic Windows',
    dpi: 600,
    language: 'Windows-GDI',
    connection: 'Windows Spooler',
    address: '\\\\PRINTSVR\\HP-WH-01',
    status: 'Ready',
    supportsCutter: false,
    supportsPeeler: false,
    supportsRfid: false,
    darkness: 10,
    speed: 10,
    mediaType: 'continuous',
  },
  {
    id: 'prn-05',
    name: 'Zebra LP 2844 Desktop (203 DPI)',
    model: 'LP 2844-Z',
    manufacturer: 'Zebra',
    dpi: 203,
    language: 'EPL',
    connection: 'USB',
    address: 'USB001 (Eltron EPL2)',
    status: 'Ready',
    supportsCutter: false,
    supportsPeeler: false,
    supportsRfid: false,
    darkness: 10,
    speed: 3,
    mediaType: 'gap',
  }
];

export const SAMPLE_DATA_SOURCES: DataSourceDefinition[] = [
  {
    id: 'ds-logistics',
    name: 'Global Logistics Shipments DB',
    type: 'sql',
    description: 'PostgreSQL live feed for warehouse pick, pack and international shipping consignments.',
    connected: true,
    currentRecordIndex: 0,
    queryOrFilter: 'SELECT * FROM shipments WHERE status = "READY_TO_SHIP" ORDER BY priority DESC LIMIT 50;',
    fields: [
      { name: 'Consignment_ID', type: 'string', sampleValue: 'CN-8849102' },
      { name: 'Customer_Name', type: 'string', sampleValue: 'Apex Medical Supplies Ltd.' },
      { name: 'Destination_City', type: 'string', sampleValue: 'Frankfurt Airport Hub' },
      { name: 'Country_Code', type: 'string', sampleValue: 'DE' },
      { name: 'Product_Desc', type: 'string', sampleValue: 'High Precision Pipettes 100ul' },
      { name: 'Product_Tamil', type: 'string', sampleValue: 'துல்லிய மருத்துவக் குழாய்கள்' },
      { name: 'Product_Hindi', type: 'string', sampleValue: 'सटीक पिपेट उपकरण' },
      { name: 'Product_Arabic', type: 'string', sampleValue: 'أنابيب مدرجة عالية الدقة' },
      { name: 'Gross_Weight_Kg', type: 'string', sampleValue: '14.85' },
      { name: 'Package_Qty', type: 'string', sampleValue: '250' },
      { name: 'Lot_Number', type: 'string', sampleValue: 'LOT-2026-F44' },
      { name: 'SSCC_Code', type: 'string', sampleValue: '003061414112345678' },
      { name: 'GTIN_14', type: 'string', sampleValue: '10061414199993' },
      { name: 'Carrier', type: 'string', sampleValue: 'DHL Global Express' },
      { name: 'Tracking_No', type: 'string', sampleValue: 'JJD01928472910' }
    ],
    records: [
      {
        id: 1,
        Consignment_ID: 'CN-8849102',
        Customer_Name: 'Apex Medical Supplies Ltd.',
        Destination_City: 'Frankfurt Airport Hub',
        Country_Code: 'DE',
        Product_Desc: 'High Precision Pipettes 100ul',
        Product_Tamil: 'துல்லிய மருத்துவக் குழாய்கள்',
        Product_Hindi: 'सटीक पिपेट उपकरण',
        Product_Arabic: 'أنابيب مدرجة عالية الدقة',
        Gross_Weight_Kg: '14.85',
        Package_Qty: '250',
        Lot_Number: 'LOT-2026-F44',
        SSCC_Code: '003061414112345678',
        GTIN_14: '10061414199993',
        Carrier: 'DHL Global Express',
        Tracking_No: 'JJD01928472910'
      },
      {
        id: 2,
        Consignment_ID: 'CN-8849103',
        Customer_Name: 'Kyoto Biopharma Logistics',
        Destination_City: 'Kansai Int Distribution Ctr',
        Country_Code: 'JP',
        Product_Desc: 'Sterile Culture Flasks 250ml',
        Product_Tamil: 'மலட்டு கலாச்சார குப்பிகள்',
        Product_Hindi: 'बाँझ संस्कृति फ्लास्क',
        Product_Arabic: 'قوارير زراعة معقمة',
        Gross_Weight_Kg: '22.10',
        Package_Qty: '400',
        Lot_Number: 'LOT-2026-K92',
        SSCC_Code: '003061414198765432',
        GTIN_14: '10061414188882',
        Carrier: 'FedEx International',
        Tracking_No: '782910384912'
      },
      {
        id: 3,
        Consignment_ID: 'CN-8849104',
        Customer_Name: 'Nordic Health Systems',
        Destination_City: 'Stockholm Arlanda Gateway',
        Country_Code: 'SE',
        Product_Desc: 'Polymer Cryogenic Vials 2.0ml',
        Product_Tamil: 'குளிர்பதன பிளாஸ்டிக் பாட்டில்கள்',
        Product_Hindi: 'क्रायोजेनिक वायल 2ml',
        Product_Arabic: 'أوعية التبريد العميق',
        Gross_Weight_Kg: '8.40',
        Package_Qty: '1000',
        Lot_Number: 'LOT-2026-N11',
        SSCC_Code: '003061414133445566',
        GTIN_14: '10061414177771',
        Carrier: 'UPS Worldwide Saver',
        Tracking_No: '1Z9999999999999999'
      }
    ]
  }
];

export const TEMPLATES: LabelDocument[] = [
  // 1. GS1 Logistics Shipping Pallet Label (100mm x 150mm)
  {
    id: 'tpl-gs1-pallet',
    schemaVersion: '1.0.0',
    name: 'GS1 Standard Logistics Shipping Pallet Label',
    description: 'Compliant with GS1 General Specifications for multi-carrier global pallet identification.',
    author: 'Principal Architect',
    created: '2026-09-14T05:00:00Z',
    modified: '2026-09-14T05:00:00Z',
    dimensions: {
      width: 100,
      height: 150,
      unit: 'mm',
      dpi: 300,
      orientation: 'portrait',
      marginLeft: 2,
      marginTop: 2,
      marginRight: 2,
      marginBottom: 2,
      cornerRadius: 1,
    },
    metadata: {
      targetPrinter: 'prn-01',
      site: 'Global HQ Distribution Center',
      version: 3,
      status: 'approved',
    },
    objects: [
      // Header Section
      {
        id: 'obj-hdr-box',
        name: 'Shipment Header Box',
        type: 'rect',
        x: 3,
        y: 3,
        width: 94,
        height: 28,
        rotation: 0,
        locked: false,
        visible: true,
        opacity: 1,
        zIndex: 1,
        shapeStyle: {
          fillColor: 'transparent',
          strokeColor: '#000000',
          strokeWidth: 0.5,
        }
      },
      {
        id: 'obj-from-lbl',
        name: 'From Company Label',
        type: 'text',
        x: 5,
        y: 4,
        width: 45,
        height: 4,
        rotation: 0,
        locked: false,
        visible: true,
        opacity: 1,
        zIndex: 2,
        text: 'FROM: LABELFORGE GLOBAL LOGISTICS',
        style: {
          fontFamily: 'Segoe UI',
          fontSize: 7,
          fontWeight: 'bold',
          fontStyle: 'normal',
          underline: false,
          strikeout: false,
          color: '#000000',
          alignment: 'left',
          direction: 'ltr',
          lineHeight: 1.2,
          letterSpacing: 0,
          wrap: false,
        }
      },
      {
        id: 'obj-to-lbl',
        name: 'Ship To Customer Title',
        type: 'text',
        x: 5,
        y: 9,
        width: 45,
        height: 5,
        rotation: 0,
        locked: false,
        visible: true,
        opacity: 1,
        zIndex: 3,
        text: 'SHIP TO: {{Customer_Name}}',
        style: {
          fontFamily: 'Segoe UI',
          fontSize: 10,
          fontWeight: 'bold',
          fontStyle: 'normal',
          underline: false,
          strikeout: false,
          color: '#000000',
          alignment: 'left',
          direction: 'ltr',
          lineHeight: 1.2,
          letterSpacing: 0,
          wrap: false,
        }
      },
      {
        id: 'obj-dest-city',
        name: 'Destination City',
        type: 'text',
        x: 5,
        y: 15,
        width: 55,
        height: 7,
        rotation: 0,
        locked: false,
        visible: true,
        opacity: 1,
        zIndex: 4,
        text: '{{Destination_City}} [{{Country_Code}}]',
        style: {
          fontFamily: 'Segoe UI',
          fontSize: 12,
          fontWeight: 'bold',
          fontStyle: 'normal',
          underline: false,
          strikeout: false,
          color: '#000000',
          alignment: 'left',
          direction: 'ltr',
          lineHeight: 1.2,
          letterSpacing: 0,
          wrap: false,
        }
      },
      {
        id: 'obj-carrier-code',
        name: 'Carrier Code Badge',
        type: 'text',
        x: 65,
        y: 5,
        width: 30,
        height: 12,
        rotation: 0,
        locked: false,
        visible: true,
        opacity: 1,
        zIndex: 5,
        text: '{{Carrier}}\nPRIORITY 1',
        style: {
          fontFamily: 'IBM Plex Mono',
          fontSize: 9,
          fontWeight: 'bold',
          fontStyle: 'normal',
          underline: false,
          strikeout: false,
          color: '#000000',
          alignment: 'right',
          direction: 'ltr',
          lineHeight: 1.3,
          letterSpacing: 0,
          wrap: false,
        }
      },
      // Middle Section - Multilingual Product Details
      {
        id: 'obj-prod-box',
        name: 'Product Details Outer Box',
        type: 'rect',
        x: 3,
        y: 33,
        width: 94,
        height: 48,
        rotation: 0,
        locked: false,
        visible: true,
        opacity: 1,
        zIndex: 6,
        shapeStyle: {
          fillColor: 'transparent',
          strokeColor: '#000000',
          strokeWidth: 0.5,
        }
      },
      {
        id: 'obj-prod-en',
        name: 'English Product Description',
        type: 'text',
        x: 5,
        y: 35,
        width: 88,
        height: 6,
        rotation: 0,
        locked: false,
        visible: true,
        opacity: 1,
        zIndex: 7,
        text: 'ITEM: {{Product_Desc}}',
        style: {
          fontFamily: 'Segoe UI',
          fontSize: 11,
          fontWeight: 'bold',
          fontStyle: 'normal',
          underline: false,
          strikeout: false,
          color: '#000000',
          alignment: 'left',
          direction: 'ltr',
          lineHeight: 1.2,
          letterSpacing: 0,
          wrap: false,
        }
      },
      // Multilingual Indic and Arabic script demonstration
      {
        id: 'obj-prod-ta',
        name: 'Tamil Description (தமிழ்)',
        type: 'text',
        x: 5,
        y: 42,
        width: 88,
        height: 6,
        rotation: 0,
        locked: false,
        visible: true,
        opacity: 1,
        zIndex: 8,
        text: 'தமிழ்: {{Product_Tamil}}',
        style: {
          fontFamily: 'Noto Sans Tamil',
          fontSize: 10,
          fontWeight: 'normal',
          fontStyle: 'normal',
          underline: false,
          strikeout: false,
          color: '#000000',
          alignment: 'left',
          direction: 'ltr',
          lineHeight: 1.2,
          letterSpacing: 0,
          wrap: false,
        }
      },
      {
        id: 'obj-prod-hi',
        name: 'Hindi Description (हिन्दी)',
        type: 'text',
        x: 5,
        y: 49,
        width: 88,
        height: 6,
        rotation: 0,
        locked: false,
        visible: true,
        opacity: 1,
        zIndex: 9,
        text: 'हिन्दी: {{Product_Hindi}}',
        style: {
          fontFamily: 'Noto Sans Devanagari',
          fontSize: 10,
          fontWeight: 'normal',
          fontStyle: 'normal',
          underline: false,
          strikeout: false,
          color: '#000000',
          alignment: 'left',
          direction: 'ltr',
          lineHeight: 1.2,
          letterSpacing: 0,
          wrap: false,
        }
      },
      {
        id: 'obj-prod-ar',
        name: 'Arabic Description (العربية)',
        type: 'text',
        x: 5,
        y: 56,
        width: 88,
        height: 6,
        rotation: 0,
        locked: false,
        visible: true,
        opacity: 1,
        zIndex: 10,
        text: 'العربية: {{Product_Arabic}}',
        style: {
          fontFamily: 'Noto Sans Arabic',
          fontSize: 10,
          fontWeight: 'normal',
          fontStyle: 'normal',
          underline: false,
          strikeout: false,
          color: '#000000',
          alignment: 'right',
          direction: 'rtl',
          lineHeight: 1.2,
          letterSpacing: 0,
          wrap: false,
        }
      },
      {
        id: 'obj-lot-qty',
        name: 'Lot & Serial Row',
        type: 'text',
        x: 5,
        y: 65,
        width: 88,
        height: 10,
        rotation: 0,
        locked: false,
        visible: true,
        opacity: 1,
        zIndex: 11,
        text: 'LOT: {{Lot_Number}}   QTY: {{Package_Qty}} EA   WT: {{Gross_Weight_Kg}} KG   SERIAL: {{SERIAL}}',
        style: {
          fontFamily: 'IBM Plex Mono',
          fontSize: 8.5,
          fontWeight: '600',
          fontStyle: 'normal',
          underline: false,
          strikeout: false,
          color: '#000000',
          alignment: 'left',
          direction: 'ltr',
          lineHeight: 1.2,
          letterSpacing: 0,
          wrap: false,
        }
      },
      // 2D QR Code & Tracking Info
      {
        id: 'obj-qr-tracking',
        name: 'Consignment QR Verification',
        type: 'qrcode',
        x: 6,
        y: 84,
        width: 24,
        height: 24,
        rotation: 0,
        locked: false,
        visible: true,
        opacity: 1,
        zIndex: 12,
        value: 'https://verify.labelforge.io/consignment/{{Consignment_ID}}?lot={{Lot_Number}}&serial={{SERIAL}}',
        barcodeStyle: {
          symbology: 'qr',
          humanReadable: false,
          humanReadableFont: 'monospace',
          humanReadableSize: 8,
          humanReadablePosition: 'none',
          moduleWidth: 0.38,
          quietZone: true,
          quietZoneSize: 2,
          errorCorrectionLevel: 'M',
          color: '#000000',
          backgroundColor: 'transparent'
        }
      },
      // 1D Intermediate GS1-128
      {
        id: 'obj-gs1-gtin-barcode',
        name: 'GS1-128 Content Barcode',
        type: 'barcode',
        x: 33,
        y: 84,
        width: 63,
        height: 24,
        rotation: 0,
        locked: false,
        visible: true,
        opacity: 1,
        zIndex: 13,
        value: '(01)10061414199993(10)LOT-2026-F44(17)280630',
        barcodeStyle: {
          symbology: 'gs1-128',
          humanReadable: true,
          humanReadableFont: 'monospace',
          humanReadableSize: 8,
          humanReadablePosition: 'bottom',
          moduleWidth: 0.33,
          quietZone: true,
          quietZoneSize: 3,
          color: '#000000',
          backgroundColor: 'transparent'
        }
      },
      // Bottom Main SSCC (Serial Shipping Container Code) - Required for GS1 Pallet
      {
        id: 'obj-sscc-title',
        name: 'SSCC Title Text',
        type: 'text',
        x: 5,
        y: 112,
        width: 90,
        height: 5,
        rotation: 0,
        locked: false,
        visible: true,
        opacity: 1,
        zIndex: 14,
        text: 'SSCC (SERIAL SHIPPING CONTAINER CODE):',
        style: {
          fontFamily: 'Segoe UI',
          fontSize: 8.5,
          fontWeight: 'bold',
          fontStyle: 'normal',
          underline: false,
          strikeout: false,
          color: '#000000',
          alignment: 'center',
          direction: 'ltr',
          lineHeight: 1.2,
          letterSpacing: 0,
          wrap: false,
        }
      },
      {
        id: 'obj-sscc-barcode',
        name: 'Master SSCC-18 Barcode',
        type: 'barcode',
        x: 6,
        y: 118,
        width: 88,
        height: 28,
        rotation: 0,
        locked: false,
        visible: true,
        opacity: 1,
        zIndex: 15,
        value: '(00)306141411234567890',
        barcodeStyle: {
          symbology: 'gs1-128',
          humanReadable: true,
          humanReadableFont: 'monospace',
          humanReadableSize: 9,
          humanReadablePosition: 'bottom',
          moduleWidth: 0.495,
          quietZone: true,
          quietZoneSize: 4,
          color: '#000000',
          backgroundColor: 'transparent'
        }
      }
    ]
  },

  // 2. Pharma Compliance Vial Label (70mm x 35mm)
  {
    id: 'tpl-pharma-vial',
    schemaVersion: '1.0.0',
    name: 'Pharma DSCSA & EU FMD Vial Identifier',
    description: 'Unit dose serialization with GS1 DataMatrix ECC 200, GTIN, Expiry, Lot and Serial Number.',
    author: 'Principal Architect',
    created: '2026-09-14T05:00:00Z',
    modified: '2026-09-14T05:00:00Z',
    dimensions: {
      width: 70,
      height: 35,
      unit: 'mm',
      dpi: 300,
      orientation: 'landscape',
      marginLeft: 1.5,
      marginTop: 1.5,
      marginRight: 1.5,
      marginBottom: 1.5,
      cornerRadius: 1,
    },
    metadata: {
      targetPrinter: 'prn-01',
      site: 'Cleanroom Packaging Suite B',
      version: 2,
      status: 'approved',
    },
    objects: [
      {
        id: 'pharma-dm',
        name: 'GS1 DataMatrix (2D Serialization)',
        type: 'datamatrix',
        x: 3,
        y: 4,
        width: 25,
        height: 25,
        rotation: 0,
        locked: false,
        visible: true,
        opacity: 1,
        zIndex: 1,
        value: '(01)00300123456789(17)281231(10)LOT-X994(21){{SERIAL}}',
        barcodeStyle: {
          symbology: 'gs1-datamatrix',
          humanReadable: false,
          humanReadableFont: 'monospace',
          humanReadableSize: 7,
          humanReadablePosition: 'none',
          moduleWidth: 0.25,
          quietZone: true,
          quietZoneSize: 1,
          color: '#000000',
          backgroundColor: 'transparent'
        }
      },
      {
        id: 'pharma-name-en',
        name: 'Drug Name Proprietary',
        type: 'text',
        x: 30,
        y: 3,
        width: 38,
        height: 6,
        rotation: 0,
        locked: false,
        visible: true,
        opacity: 1,
        zIndex: 2,
        text: 'Remdesivir Injectable 100mg/vial',
        style: {
          fontFamily: 'Segoe UI',
          fontSize: 9,
          fontWeight: 'bold',
          fontStyle: 'normal',
          underline: false,
          strikeout: false,
          color: '#000000',
          alignment: 'left',
          direction: 'ltr',
          lineHeight: 1.2,
          letterSpacing: 0,
          wrap: true,
        }
      },
      {
        id: 'pharma-multilingual',
        name: 'Multilingual Warning (Tamil/Hindi)',
        type: 'text',
        x: 30,
        y: 10,
        width: 38,
        height: 5,
        rotation: 0,
        locked: false,
        visible: true,
        opacity: 1,
        zIndex: 3,
        text: 'மருத்துவ பயன்பாட்டிற்கு மட்டும் | केवल Rx',
        style: {
          fontFamily: 'Noto Sans Tamil',
          fontSize: 7.5,
          fontWeight: 'normal',
          fontStyle: 'normal',
          underline: false,
          strikeout: false,
          color: '#1a56db',
          alignment: 'left',
          direction: 'ltr',
          lineHeight: 1.2,
          letterSpacing: 0,
          wrap: false,
        }
      },
      {
        id: 'pharma-data-list',
        name: 'Human Readable AIs',
        type: 'text',
        x: 30,
        y: 16,
        width: 38,
        height: 16,
        rotation: 0,
        locked: false,
        visible: true,
        opacity: 1,
        zIndex: 4,
        text: 'GTIN: 00300123456789\nEXP:  2028-12-31\nLOT:  LOT-X994\nSN:   {{SERIAL}}',
        style: {
          fontFamily: 'IBM Plex Mono',
          fontSize: 7,
          fontWeight: '600',
          fontStyle: 'normal',
          underline: false,
          strikeout: false,
          color: '#000000',
          alignment: 'left',
          direction: 'ltr',
          lineHeight: 1.35,
          letterSpacing: 0,
          wrap: false,
        }
      }
    ]
  }
];

export const SAMPLE_TEMPLATES: LabelDocument[] = TEMPLATES;

export const SAMPLE_WORKFLOWS: AutomationWorkflow[] = [
  {
    id: 'wf-csv-spooler',
    name: 'Inbound CSV Drop & Auto-Spooler',
    description: 'Watches /var/spool/labelforge for ERP drop files, evaluates preflight, and sends ZPL directly to Zebra ZT410.',
    active: true,
    triggerType: 'file-drop',
    executionCount: 142,
    lastExecuted: '2026-09-14 05:01:22',
    lastStatus: 'success',
    nodes: [
      { id: 'n1', type: 'file-drop', title: 'File Drop Watcher (*.csv)', category: 'trigger', config: { path: '/spool/inbox/*.csv', intervalSec: 5 }, enabled: true, status: 'idle' },
      { id: 'n2', type: 'parse-csv', title: 'CSV Schema & Field Mapper', category: 'transform', config: { delimiter: ',', trim: true }, enabled: true, status: 'idle' },
      { id: 'n3', type: 'preflight-check', title: 'Enterprise Preflight Check', category: 'transform', config: { haltOnError: true }, enabled: true, status: 'idle' },
      { id: 'n4', type: 'assign-printer', title: 'Route to Zebra ZT410 (300 DPI)', category: 'print', config: { printerId: 'prn-01' }, enabled: true, status: 'idle' },
      { id: 'n5', type: 'execute-print', title: 'Direct Socket Print (Port 9100)', category: 'print', config: { format: 'ZPL', verifyCompletion: true }, enabled: true, status: 'idle' },
      { id: 'n6', type: 'archive-payload', title: 'Archive to /spool/processed', category: 'post-process', config: { retentionDays: 90 }, enabled: true, status: 'idle' }
    ]
  },
  {
    id: 'wf-rest-webhook',
    name: 'SAP / NetSuite Real-time Print Webhook',
    description: 'REST API listener on /api/v1/jobs for on-demand packing bench label generation.',
    active: true,
    triggerType: 'webhook',
    executionCount: 529,
    lastExecuted: '2026-09-14 04:58:10',
    lastStatus: 'success',
    nodes: [
      { id: 'w1', type: 'webhook', title: 'POST /api/v1/jobs Webhook', category: 'trigger', config: { auth: 'Bearer Token', rateLimit: 100 }, enabled: true, status: 'idle' },
      { id: 'w2', type: 'validate-data', title: 'JSON Schema Validation', category: 'transform', config: { strict: true }, enabled: true, status: 'idle' },
      { id: 'w3', type: 'execute-print', title: 'Send to TSC TTP-244 (TSPL)', category: 'print', config: { printerId: 'prn-02' }, enabled: true, status: 'idle' },
      { id: 'w4', type: 'send-webhook', title: 'POST Callback to ERP', category: 'post-process', config: { url: 'https://erp.example.com/events/printed' }, enabled: true, status: 'idle' }
    ]
  }
];

export const SAMPLE_WORKFLOW: AutomationWorkflow = SAMPLE_WORKFLOWS[0];

export interface MultilingualFontSpec {
  family: string;
  displayName: string;
  category: string;
  direction?: 'ltr' | 'rtl';
  sampleText: string;
}

export const MULTILINGUAL_FONTS: MultilingualFontSpec[] = [
  {
    family: 'Segoe UI',
    displayName: 'Segoe UI (Standard Latin & Industrial)',
    category: 'sans-serif',
    direction: 'ltr',
    sampleText: 'BARCODE & THERMAL SPECIFICATION TEST 123456',
  },
  {
    family: 'IBM Plex Mono',
    displayName: 'IBM Plex Mono (Monospace Logistics)',
    category: 'monospace',
    direction: 'ltr',
    sampleText: 'GTIN: (01)00614141999996 LOT: LOT-2026-X',
  },
  {
    family: 'Noto Sans Tamil',
    displayName: 'Noto Sans Tamil (தமிழ் - South India / Sri Lanka / Singapore)',
    category: 'indic',
    direction: 'ltr',
    sampleText: 'மருத்துவ தயாரிப்பு விவரக்குறிப்பு - தொகுதி எண்: 98842',
  },
  {
    family: 'Noto Sans Devanagari',
    displayName: 'Noto Sans Devanagari (हिन्दी - India & Nepal)',
    category: 'indic',
    direction: 'ltr',
    sampleText: 'गुणवत्ता आश्वासन एवं औद्योगिक मुद्रण प्रणाली',
  },
  {
    family: 'Noto Sans Arabic',
    displayName: 'Noto Sans Arabic (العربية - Middle East / North Africa RTL)',
    category: 'arabic',
    direction: 'rtl',
    sampleText: 'مستودع التوزيع الدولي - شحنة رقمية معتمدة',
  },
  {
    family: 'Noto Sans SC',
    displayName: 'Noto Sans SC (简体中文 - Simplified Chinese)',
    category: 'cjk',
    direction: 'ltr',
    sampleText: '企业级热敏标签设计与工业级打印系统',
  },
  {
    family: 'Noto Sans JP',
    displayName: 'Noto Sans JP (日本語 - Japanese)',
    category: 'cjk',
    direction: 'ltr',
    sampleText: '高精度サーマルプリンター制御およびバーコード検証',
  },
];

