/**
 * LabelForge Platform - Production Template Library Presets
 * Real, industrial, vector-fidelity LabelDocument templates across enterprise verticals.
 */

import { TemplateRecord, LabelSizePreset } from '../types/template';

export const BUILTIN_TEMPLATE_LIBRARY: TemplateRecord[] = [
  // 1. GS1 Logistics Shipping Pallet Label
  {
    id: 'tpl-gs1-128-logistics',
    name: 'GS1-128 Logistics Shipping & Pallet Label',
    description: 'Standard GS1 compliant international freight pallet label featuring SSCC-18 logistics barcode and dual 2D QR fast scan routing.',
    category: 'shipping',
    industry: 'Logistics & Warehousing',
    tags: ['GS1-128', 'SSCC', 'Pallet', 'Shipping', 'Logistics', 'Freight'],
    isBuiltin: true,
    isFavorite: true,
    created: '2026-09-01T08:00:00Z',
    modified: '2026-09-18T10:30:00Z',
    author: 'LabelForge Standards Engineering',
    version: 1,
    isReadOnly: true,
    primarySymbology: 'gs1-128',
    supportsQr: true,
    elementCount: 11,
    usageCount: 142,
    variables: [
      { key: 'Customer_Name', label: 'Consignee / Customer Name', type: 'text', defaultValue: 'ACME LOGISTICS FREIGHT TERMINAL', sampleValue: 'ACME LOGISTICS FREIGHT TERMINAL', required: true },
      { key: 'Destination_City', label: 'Destination Hub & Postal Code', type: 'text', defaultValue: 'MEMPHIS DISTRIBUTION HUB - TN 38118', sampleValue: 'MEMPHIS DISTRIBUTION HUB - TN 38118', required: true },
      { key: 'Product_Desc', label: 'Commodity Description', type: 'text', defaultValue: 'HIGH-PRECISION SERVO ACTUATORS', sampleValue: 'HIGH-PRECISION SERVO ACTUATORS', required: true },
      { key: 'Lot_Number', label: 'Batch / Lot Code', type: 'text', defaultValue: 'LOT-2026-09X', sampleValue: 'LOT-2026-09X', required: true },
      { key: 'Package_Qty', label: 'Package Unit Quantity', type: 'text', defaultValue: '48', sampleValue: '48', required: true },
      { key: 'Gross_Weight_Kg', label: 'Gross Pallet Weight (kg)', type: 'text', defaultValue: '342.50', sampleValue: '342.50' },
      { key: 'SSCC_Code', label: 'SSCC-18 Identifier', type: 'barcode', defaultValue: '(00) 3 0012345 555555555 8', sampleValue: '(00) 3 0012345 555555555 8', required: true },
      { key: 'Consignment_ID', label: 'Tracking Consignment Number', type: 'text', defaultValue: 'CN-88492041-US', sampleValue: 'CN-88492041-US' }
    ],
    sampleData: {
      Customer_Name: 'ACME LOGISTICS FREIGHT TERMINAL',
      Destination_City: 'MEMPHIS HUB - TN 38118',
      Product_Desc: 'HIGH-PRECISION SERVO ACTUATORS',
      Lot_Number: 'LOT-2026-09X',
      Package_Qty: '48',
      Gross_Weight_Kg: '342.50',
      SSCC_Code: '(00)300123455555555558',
      Consignment_ID: 'CN-88492041-US'
    },
    document: {
      id: 'tpl-gs1-128-logistics',
      schemaVersion: '1.0.0',
      name: 'GS1-128 Logistics Shipping & Pallet Label',
      description: 'Standard GS1 compliant international freight pallet label featuring SSCC-18 logistics barcode and dual 2D QR fast scan routing.',
      author: 'LabelForge Standards Engineering',
      created: '2026-09-01T08:00:00Z',
      modified: '2026-09-18T10:30:00Z',
      dimensions: {
        width: 100,
        height: 150,
        unit: 'mm',
        dpi: 300,
        orientation: 'portrait',
        marginLeft: 3,
        marginTop: 3,
        marginRight: 3,
        marginBottom: 3,
        cornerRadius: 0
      },
      metadata: { targetPrinter: 'prn-01', site: 'Warehouse Bay 4', version: 3, status: 'approved' },
      objects: [
        {
          id: 'gs1-hdr-box',
          name: 'Header Background Bar',
          type: 'rect',
          x: 4,
          y: 4,
          width: 92,
          height: 12,
          rotation: 0,
          locked: true,
          visible: true,
          opacity: 1,
          zIndex: 1,
          shapeStyle: { fillColor: '#1e293b', strokeColor: '#0f172a', strokeWidth: 0.5 }
        },
        {
          id: 'gs1-hdr-title',
          name: 'Logistics Header Title',
          type: 'text',
          x: 6,
          y: 6,
          width: 88,
          height: 8,
          rotation: 0,
          locked: true,
          visible: true,
          opacity: 1,
          zIndex: 2,
          text: 'GS1 GLOBAL LOGISTICS TRANSPORT LABEL',
          style: { fontFamily: 'Segoe UI', fontSize: 9.5, fontWeight: 'bold', color: '#ffffff', alignment: 'center' }
        },
        {
          id: 'gs1-ship-to-title',
          name: 'Ship To Header',
          type: 'text',
          x: 5,
          y: 18,
          width: 30,
          height: 4,
          rotation: 0,
          locked: false,
          visible: true,
          opacity: 1,
          zIndex: 3,
          text: 'SHIP TO / CONSIGNEE:',
          style: { fontFamily: 'Segoe UI', fontSize: 7, fontWeight: 'bold', color: '#64748b', alignment: 'left' }
        },
        {
          id: 'gs1-ship-to-name',
          name: 'Customer Name Text',
          type: 'text',
          x: 5,
          y: 23,
          width: 88,
          height: 6,
          rotation: 0,
          locked: false,
          visible: true,
          opacity: 1,
          zIndex: 4,
          text: '{{Customer_Name}}',
          style: { fontFamily: 'Segoe UI', fontSize: 11, fontWeight: 'bold', color: '#000000', alignment: 'left' }
        },
        {
          id: 'gs1-dest-hub',
          name: 'Destination Hub Text',
          type: 'text',
          x: 5,
          y: 30,
          width: 88,
          height: 6,
          rotation: 0,
          locked: false,
          visible: true,
          opacity: 1,
          zIndex: 5,
          text: 'HUB: {{Destination_City}}',
          style: { fontFamily: 'IBM Plex Mono', fontSize: 9.5, fontWeight: 'bold', color: '#0f172a', alignment: 'left' }
        },
        {
          id: 'gs1-div-1',
          name: 'Divider Line 1',
          type: 'line',
          x: 4,
          y: 38,
          width: 92,
          height: 0.5,
          rotation: 0,
          locked: true,
          visible: true,
          opacity: 1,
          zIndex: 6,
          shapeStyle: { fillColor: '#000000', strokeColor: '#000000', strokeWidth: 0.8 }
        },
        {
          id: 'gs1-prod-desc',
          name: 'Product Description',
          type: 'text',
          x: 5,
          y: 41,
          width: 88,
          height: 6,
          rotation: 0,
          locked: false,
          visible: true,
          opacity: 1,
          zIndex: 7,
          text: 'ITEM: {{Product_Desc}}',
          style: { fontFamily: 'Segoe UI', fontSize: 9, fontWeight: '600', color: '#000000', alignment: 'left' }
        },
        {
          id: 'gs1-meta-row',
          name: 'Lot and Quantity Metadata',
          type: 'text',
          x: 5,
          y: 48,
          width: 88,
          height: 6,
          rotation: 0,
          locked: false,
          visible: true,
          opacity: 1,
          zIndex: 8,
          text: 'LOT: {{Lot_Number}} | QTY: {{Package_Qty}} EA | WT: {{Gross_Weight_Kg}} KG',
          style: { fontFamily: 'IBM Plex Mono', fontSize: 8, fontWeight: '600', color: '#334155', alignment: 'left' }
        },
        {
          id: 'gs1-qr-code',
          name: 'Carrier Fast Scan QR',
          type: 'qrcode',
          x: 6,
          y: 58,
          width: 26,
          height: 26,
          rotation: 0,
          locked: false,
          visible: true,
          opacity: 1,
          zIndex: 9,
          value: 'https://tracking.labelforge.io/ship/{{Consignment_ID}}?sscc={{SSCC_Code}}',
          barcodeStyle: {
            symbology: 'qr',
            humanReadable: false,
            humanReadableFont: 'monospace',
            humanReadableSize: 8,
            humanReadablePosition: 'none',
            moduleWidth: 0.35,
            quietZone: true,
            quietZoneSize: 2,
            color: '#000000',
            backgroundColor: '#ffffff'
          }
        },
        {
          id: 'gs1-qr-desc',
          name: 'QR Scan Instruction',
          type: 'text',
          x: 35,
          y: 62,
          width: 58,
          height: 18,
          rotation: 0,
          locked: false,
          visible: true,
          opacity: 1,
          zIndex: 10,
          text: 'CARRIER DOCK INGESTION:\nScan QR for instant electronic BOL manifest & customs pre-clearance.',
          style: { fontFamily: 'Segoe UI', fontSize: 7.5, fontWeight: 'normal', color: '#475569', alignment: 'left', wrap: true }
        },
        {
          id: 'gs1-sscc-barcode',
          name: 'SSCC Logistics Barcode',
          type: 'barcode',
          x: 5,
          y: 92,
          width: 90,
          height: 52,
          rotation: 0,
          locked: false,
          visible: true,
          opacity: 1,
          zIndex: 11,
          value: '{{SSCC_Code}}',
          barcodeStyle: {
            symbology: 'gs1-128',
            humanReadable: true,
            humanReadableFont: 'monospace',
            humanReadableSize: 9,
            humanReadablePosition: 'bottom',
            moduleWidth: 0.38,
            quietZone: true,
            quietZoneSize: 3,
            color: '#000000',
            backgroundColor: '#ffffff'
          }
        }
      ]
    }
  },

  // 2. Retail Apparel Price & Size Tag
  {
    id: 'tpl-retail-price-tag',
    name: 'Retail Apparel Price Tag with EAN-13 & Brand Mark',
    description: 'High-contrast fashion garment tag featuring bold retail price typography, size callout, SKU, and EAN-13 point-of-sale barcode.',
    category: 'retail',
    industry: 'Retail & Fashion',
    tags: ['Retail', 'Apparel', 'Price Tag', 'EAN-13', 'POS', 'Garment'],
    isBuiltin: true,
    isFavorite: true,
    created: '2026-09-02T08:00:00Z',
    modified: '2026-09-15T14:20:00Z',
    author: 'LabelForge Retail Solutions',
    version: 2,
    isReadOnly: true,
    primarySymbology: 'ean13',
    supportsQr: false,
    elementCount: 8,
    usageCount: 98,
    variables: [
      { key: 'Brand_Name', label: 'Fashion Brand / Collection', type: 'text', defaultValue: 'AURA COLLECTIVE', sampleValue: 'AURA COLLECTIVE', required: true },
      { key: 'Garment_Title', label: 'Item Name / Style', type: 'text', defaultValue: 'ORGANIC COTTON OVERSIZED TEE', sampleValue: 'ORGANIC COTTON OVERSIZED TEE', required: true },
      { key: 'Garment_Color', label: 'Colorway', type: 'text', defaultValue: 'SLATE WASHED NAVY', sampleValue: 'SLATE WASHED NAVY' },
      { key: 'Garment_Size', label: 'Size Identifier', type: 'text', defaultValue: 'L', sampleValue: 'L', required: true },
      { key: 'Retail_Price', label: 'Retail Price (Currency Included)', type: 'text', defaultValue: '$48.00', sampleValue: '$48.00', required: true },
      { key: 'EAN_Code', label: '13-Digit EAN Barcode', type: 'barcode', defaultValue: '5012345678900', sampleValue: '5012345678900', required: true },
      { key: 'SKU_Number', label: 'Internal SKU', type: 'text', defaultValue: 'SKU: AC-2026-TS-049', sampleValue: 'SKU: AC-2026-TS-049' }
    ],
    sampleData: {
      Brand_Name: 'AURA COLLECTIVE',
      Garment_Title: 'ORGANIC COTTON OVERSIZED TEE',
      Garment_Color: 'SLATE WASHED NAVY',
      Garment_Size: 'L',
      Retail_Price: '$48.00',
      EAN_Code: '5012345678900',
      SKU_Number: 'SKU: AC-2026-TS-049'
    },
    document: {
      id: 'tpl-retail-price-tag',
      schemaVersion: '1.0.0',
      name: 'Retail Apparel Price Tag with EAN-13 & Brand Mark',
      description: 'High-contrast fashion garment tag featuring bold retail price typography, size callout, SKU, and EAN-13 point-of-sale barcode.',
      author: 'LabelForge Retail Solutions',
      created: '2026-09-02T08:00:00Z',
      modified: '2026-09-15T14:20:00Z',
      dimensions: {
        width: 50,
        height: 90,
        unit: 'mm',
        dpi: 300,
        orientation: 'portrait',
        marginLeft: 2,
        marginTop: 2,
        marginRight: 2,
        marginBottom: 2,
        cornerRadius: 2
      },
      metadata: { targetPrinter: 'prn-02', site: 'Retail Flagship Store', version: 2, status: 'approved' },
      objects: [
        {
          id: 'retail-brand-title',
          name: 'Brand Name',
          type: 'text',
          x: 2,
          y: 6,
          width: 46,
          height: 6,
          rotation: 0,
          locked: false,
          visible: true,
          opacity: 1,
          zIndex: 1,
          text: '{{Brand_Name}}',
          style: { fontFamily: 'Segoe UI', fontSize: 11, fontWeight: 'bold', color: '#0f172a', alignment: 'center' }
        },
        {
          id: 'retail-item-name',
          name: 'Item Name',
          type: 'text',
          x: 3,
          y: 14,
          width: 44,
          height: 8,
          rotation: 0,
          locked: false,
          visible: true,
          opacity: 1,
          zIndex: 2,
          text: '{{Garment_Title}}',
          style: { fontFamily: 'Segoe UI', fontSize: 7.5, fontWeight: '600', color: '#475569', alignment: 'center', wrap: true }
        },
        {
          id: 'retail-color',
          name: 'Color Specifier',
          type: 'text',
          x: 3,
          y: 24,
          width: 44,
          height: 4,
          rotation: 0,
          locked: false,
          visible: true,
          opacity: 1,
          zIndex: 3,
          text: 'COLOR: {{Garment_Color}}',
          style: { fontFamily: 'Segoe UI', fontSize: 6.5, fontWeight: 'normal', color: '#64748b', alignment: 'center' }
        },
        {
          id: 'retail-size-box',
          name: 'Size Badge Outline',
          type: 'rect',
          x: 18,
          y: 30,
          width: 14,
          height: 10,
          rotation: 0,
          locked: true,
          visible: true,
          opacity: 1,
          zIndex: 4,
          shapeStyle: { fillColor: '#f1f5f9', strokeColor: '#0f172a', strokeWidth: 0.6, borderRadius: 1.5 }
        },
        {
          id: 'retail-size-val',
          name: 'Size Label',
          type: 'text',
          x: 18,
          y: 31,
          width: 14,
          height: 8,
          rotation: 0,
          locked: false,
          visible: true,
          opacity: 1,
          zIndex: 5,
          text: '{{Garment_Size}}',
          style: { fontFamily: 'Segoe UI', fontSize: 14, fontWeight: 'bold', color: '#0f172a', alignment: 'center' }
        },
        {
          id: 'retail-price-val',
          name: 'Retail Price Display',
          type: 'text',
          x: 2,
          y: 43,
          width: 46,
          height: 9,
          rotation: 0,
          locked: false,
          visible: true,
          opacity: 1,
          zIndex: 6,
          text: '{{Retail_Price}}',
          style: { fontFamily: 'Segoe UI', fontSize: 16, fontWeight: 'bold', color: '#000000', alignment: 'center' }
        },
        {
          id: 'retail-ean-barcode',
          name: 'POS EAN-13 Barcode',
          type: 'barcode',
          x: 4,
          y: 54,
          width: 42,
          height: 28,
          rotation: 0,
          locked: false,
          visible: true,
          opacity: 1,
          zIndex: 7,
          value: '{{EAN_Code}}',
          barcodeStyle: {
            symbology: 'ean13',
            humanReadable: true,
            humanReadableFont: 'monospace',
            humanReadableSize: 8,
            humanReadablePosition: 'bottom',
            moduleWidth: 0.33,
            quietZone: true,
            quietZoneSize: 2,
            color: '#000000',
            backgroundColor: '#ffffff'
          }
        },
        {
          id: 'retail-sku-text',
          name: 'Internal SKU Text',
          type: 'text',
          x: 2,
          y: 84,
          width: 46,
          height: 4,
          rotation: 0,
          locked: false,
          visible: true,
          opacity: 1,
          zIndex: 8,
          text: '{{SKU_Number}}',
          style: { fontFamily: 'IBM Plex Mono', fontSize: 6.5, fontWeight: 'normal', color: '#64748b', alignment: 'center' }
        }
      ]
    }
  },

  // 3. FDA UDI Medical Device Matrix Label
  {
    id: 'tpl-fda-udi-medical',
    name: 'FDA UDI Medical Device Label (GS1 DataMatrix)',
    description: 'Compliant medical device identification label meeting FDA Unique Device Identification (UDI) regulations with GS1 DataMatrix (DI+PI).',
    category: 'healthcare',
    industry: 'Healthcare & Medical Devices',
    tags: ['FDA', 'UDI', 'Medical', 'GS1-DataMatrix', 'Sterile', 'Healthcare'],
    isBuiltin: true,
    isFavorite: false,
    created: '2026-09-03T08:00:00Z',
    modified: '2026-09-17T09:10:00Z',
    author: 'Medical Device Compliance Division',
    version: 1,
    isReadOnly: true,
    primarySymbology: 'gs1-datamatrix',
    supportsQr: false,
    elementCount: 10,
    usageCount: 65,
    variables: [
      { key: 'Device_Name', label: 'Medical Device Generic Name', type: 'text', defaultValue: 'BIO-COMPATIBLE VASCULAR STENT CATHETER', sampleValue: 'BIO-COMPATIBLE VASCULAR STENT CATHETER', required: true },
      { key: 'Model_Number', label: 'Catalog / Model Reference', type: 'text', defaultValue: 'REF: VST-2026-04', sampleValue: 'REF: VST-2026-04', required: true },
      { key: 'GTIN_DI', label: 'Device Identifier (GTIN-14)', type: 'text', defaultValue: '(01) 00840123456789', sampleValue: '(01) 00840123456789', required: true },
      { key: 'Expiry_Date', label: 'Sterility Expiry Date (YYYY-MM-DD)', type: 'date', defaultValue: '2029-08-31', sampleValue: '2029-08-31', required: true },
      { key: 'Lot_Number', label: 'Sterilization Batch Lot', type: 'text', defaultValue: 'LOT: ST-99201A', sampleValue: 'LOT: ST-99201A', required: true },
      { key: 'Serial_Number', label: 'Unit Serial Number', type: 'text', defaultValue: 'SN: 882049102', sampleValue: 'SN: 882049102', required: true },
      { key: 'UDI_String', label: 'GS1 UDI Full Human Readable String', type: 'text', defaultValue: '(01)00840123456789(17)290831(10)ST99201A(21)882049102', sampleValue: '(01)00840123456789(17)290831(10)ST99201A(21)882049102' }
    ],
    sampleData: {
      Device_Name: 'BIO-COMPATIBLE VASCULAR STENT CATHETER',
      Model_Number: 'REF: VST-2026-04',
      GTIN_DI: '(01) 00840123456789',
      Expiry_Date: '2029-08-31',
      Lot_Number: 'LOT: ST-99201A',
      Serial_Number: 'SN: 882049102',
      UDI_String: '(01)00840123456789(17)290831(10)ST99201A(21)882049102'
    },
    document: {
      id: 'tpl-fda-udi-medical',
      schemaVersion: '1.0.0',
      name: 'FDA UDI Medical Device Label (GS1 DataMatrix)',
      description: 'Compliant medical device identification label meeting FDA Unique Device Identification (UDI) regulations with GS1 DataMatrix (DI+PI).',
      author: 'Medical Device Compliance Division',
      created: '2026-09-03T08:00:00Z',
      modified: '2026-09-17T09:10:00Z',
      dimensions: {
        width: 80,
        height: 45,
        unit: 'mm',
        dpi: 300,
        orientation: 'landscape',
        marginLeft: 2,
        marginTop: 2,
        marginRight: 2,
        marginBottom: 2,
        cornerRadius: 1
      },
      metadata: { targetPrinter: 'prn-03', site: 'Cleanroom Lab Alpha', version: 1, status: 'approved' },
      objects: [
        {
          id: 'udi-device-title',
          name: 'Device Trade Name',
          type: 'text',
          x: 3,
          y: 3,
          width: 74,
          height: 6,
          rotation: 0,
          locked: false,
          visible: true,
          opacity: 1,
          zIndex: 1,
          text: '{{Device_Name}}',
          style: { fontFamily: 'Segoe UI', fontSize: 8.5, fontWeight: 'bold', color: '#0f172a', alignment: 'left' }
        },
        {
          id: 'udi-ref-box',
          name: 'Model Catalog Ref',
          type: 'text',
          x: 3,
          y: 10,
          width: 48,
          height: 4,
          rotation: 0,
          locked: false,
          visible: true,
          opacity: 1,
          zIndex: 2,
          text: '{{Model_Number}} | STERILE EO | SINGLE USE ONLY',
          style: { fontFamily: 'Segoe UI', fontSize: 6.5, fontWeight: '600', color: '#475569', alignment: 'left' }
        },
        {
          id: 'udi-datamatrix',
          name: 'GS1 2D DataMatrix Symbol',
          type: 'datamatrix',
          x: 3,
          y: 16,
          width: 25,
          height: 25,
          rotation: 0,
          locked: false,
          visible: true,
          opacity: 1,
          zIndex: 3,
          value: '{{UDI_String}}',
          barcodeStyle: {
            symbology: 'gs1-datamatrix',
            humanReadable: false,
            humanReadableFont: 'monospace',
            humanReadableSize: 8,
            humanReadablePosition: 'none',
            moduleWidth: 0.35,
            quietZone: true,
            quietZoneSize: 2,
            color: '#000000',
            backgroundColor: '#ffffff'
          }
        },
        {
          id: 'udi-gtin-line',
          name: 'DI (GTIN) Line',
          type: 'text',
          x: 30,
          y: 16,
          width: 47,
          height: 4,
          rotation: 0,
          locked: false,
          visible: true,
          opacity: 1,
          zIndex: 4,
          text: 'DI: {{GTIN_DI}}',
          style: { fontFamily: 'IBM Plex Mono', fontSize: 6.8, fontWeight: 'bold', color: '#0f172a', alignment: 'left' }
        },
        {
          id: 'udi-exp-line',
          name: 'Expiry Date Line',
          type: 'text',
          x: 30,
          y: 21,
          width: 47,
          height: 4,
          rotation: 0,
          locked: false,
          visible: true,
          opacity: 1,
          zIndex: 5,
          text: 'USE BY (17): {{Expiry_Date}}',
          style: { fontFamily: 'IBM Plex Mono', fontSize: 6.8, fontWeight: 'bold', color: '#0f172a', alignment: 'left' }
        },
        {
          id: 'udi-lot-line',
          name: 'Lot & Serial Line',
          type: 'text',
          x: 30,
          y: 26,
          width: 47,
          height: 4,
          rotation: 0,
          locked: false,
          visible: true,
          opacity: 1,
          zIndex: 6,
          text: '{{Lot_Number}} | {{Serial_Number}}',
          style: { fontFamily: 'IBM Plex Mono', fontSize: 6.8, fontWeight: 'bold', color: '#0f172a', alignment: 'left' }
        },
        {
          id: 'udi-hri-full',
          name: 'Full Human Readable String',
          type: 'text',
          x: 30,
          y: 32,
          width: 47,
          height: 8,
          rotation: 0,
          locked: false,
          visible: true,
          opacity: 1,
          zIndex: 7,
          text: 'UDI: {{UDI_String}}',
          style: { fontFamily: 'IBM Plex Mono', fontSize: 5.5, fontWeight: 'normal', color: '#64748b', alignment: 'left', wrap: true }
        }
      ]
    }
  },

  // 4. Chemical Drum GHS Hazard Warning Placard
  {
    id: 'tpl-ghs-chemical-placard',
    name: 'Chemical Drum GHS Hazard Warning Placard',
    description: 'OSHA / GHS compliant industrial chemical drum label with standardized red hazard diamonds, signal word (DANGER), and Code 128 batch identifier.',
    category: 'warning',
    industry: 'Chemical & Hazardous Materials',
    tags: ['GHS', 'OSHA', 'Chemical', 'Hazard', 'Danger', 'Code 128'],
    isBuiltin: true,
    isFavorite: false,
    created: '2026-09-04T08:00:00Z',
    modified: '2026-09-12T11:00:00Z',
    author: 'EHS Safety Regulatory Group',
    version: 1,
    isReadOnly: true,
    primarySymbology: 'code128',
    supportsQr: false,
    elementCount: 11,
    usageCount: 42,
    variables: [
      { key: 'Chemical_Name', label: 'IUPAC / Commercial Chemical Name', type: 'text', defaultValue: 'ACETONE HPLC GRADE 99.8%', sampleValue: 'ACETONE HPLC GRADE 99.8%', required: true },
      { key: 'CAS_Number', label: 'CAS Registry Number', type: 'text', defaultValue: 'CAS: 67-64-1 | UN: 1090', sampleValue: 'CAS: 67-64-1 | UN: 1090', required: true },
      { key: 'Signal_Word', label: 'Signal Word (DANGER / WARNING)', type: 'text', defaultValue: 'DANGER', sampleValue: 'DANGER', required: true },
      { key: 'Hazard_Statements', label: 'Hazard Summary', type: 'text', defaultValue: 'H225: Highly flammable liquid and vapor.\nH319: Causes serious eye irritation.\nH336: May cause drowsiness or dizziness.', sampleValue: 'H225: Highly flammable liquid and vapor.\nH319: Causes serious eye irritation.\nH336: May cause drowsiness or dizziness.' },
      { key: 'Batch_Barcode', label: 'Batch Identifier (Code 128)', type: 'barcode', defaultValue: 'CHM-2026-ACT-9902', sampleValue: 'CHM-2026-ACT-9902', required: true }
    ],
    sampleData: {
      Chemical_Name: 'ACETONE HPLC GRADE 99.8%',
      CAS_Number: 'CAS: 67-64-1 | UN: 1090',
      Signal_Word: 'DANGER',
      Hazard_Statements: 'H225: Highly flammable liquid and vapor.\nH319: Causes serious eye irritation.\nH336: May cause drowsiness or dizziness.',
      Batch_Barcode: 'CHM-2026-ACT-9902'
    },
    document: {
      id: 'tpl-ghs-chemical-placard',
      schemaVersion: '1.0.0',
      name: 'Chemical Drum GHS Hazard Warning Placard',
      description: 'OSHA / GHS compliant industrial chemical drum label with standardized red hazard diamonds, signal word (DANGER), and Code 128 batch identifier.',
      author: 'EHS Safety Regulatory Group',
      created: '2026-09-04T08:00:00Z',
      modified: '2026-09-12T11:00:00Z',
      dimensions: {
        width: 105,
        height: 74,
        unit: 'mm',
        dpi: 300,
        orientation: 'landscape',
        marginLeft: 2,
        marginTop: 2,
        marginRight: 2,
        marginBottom: 2,
        cornerRadius: 0
      },
      metadata: { targetPrinter: 'prn-01', site: 'Chemical Processing Site B', version: 1, status: 'approved' },
      objects: [
        {
          id: 'ghs-danger-bar',
          name: 'Signal Word Banner',
          type: 'rect',
          x: 3,
          y: 3,
          width: 99,
          height: 10,
          rotation: 0,
          locked: true,
          visible: true,
          opacity: 1,
          zIndex: 1,
          shapeStyle: { fillColor: '#dc2626', strokeColor: '#991b1b', strokeWidth: 0.5 }
        },
        {
          id: 'ghs-signal-text',
          name: 'Signal Word Text',
          type: 'text',
          x: 5,
          y: 4.5,
          width: 95,
          height: 7,
          rotation: 0,
          locked: true,
          visible: true,
          opacity: 1,
          zIndex: 2,
          text: '{{Signal_Word}} - HAZARDOUS MATERIAL',
          style: { fontFamily: 'Segoe UI', fontSize: 11, fontWeight: 'bold', color: '#ffffff', alignment: 'center' }
        },
        {
          id: 'ghs-chem-name',
          name: 'Chemical Name',
          type: 'text',
          x: 4,
          y: 15,
          width: 97,
          height: 7,
          rotation: 0,
          locked: false,
          visible: true,
          opacity: 1,
          zIndex: 3,
          text: '{{Chemical_Name}}',
          style: { fontFamily: 'Segoe UI', fontSize: 11, fontWeight: 'bold', color: '#0f172a', alignment: 'left' }
        },
        {
          id: 'ghs-cas-text',
          name: 'CAS Registry Info',
          type: 'text',
          x: 4,
          y: 22,
          width: 97,
          height: 4,
          rotation: 0,
          locked: false,
          visible: true,
          opacity: 1,
          zIndex: 4,
          text: '{{CAS_Number}}',
          style: { fontFamily: 'IBM Plex Mono', fontSize: 7.5, fontWeight: 'bold', color: '#475569', alignment: 'left' }
        },
        {
          id: 'ghs-pictogram-1',
          name: 'Flammable Red Diamond Frame',
          type: 'rect',
          x: 6,
          y: 29,
          width: 14,
          height: 14,
          rotation: 45,
          locked: true,
          visible: true,
          opacity: 1,
          zIndex: 5,
          shapeStyle: { fillColor: '#ffffff', strokeColor: '#dc2626', strokeWidth: 1.2 }
        },
        {
          id: 'ghs-pictogram-2',
          name: 'Health Hazard Red Diamond Frame',
          type: 'rect',
          x: 23,
          y: 29,
          width: 14,
          height: 14,
          rotation: 45,
          locked: true,
          visible: true,
          opacity: 1,
          zIndex: 6,
          shapeStyle: { fillColor: '#ffffff', strokeColor: '#dc2626', strokeWidth: 1.2 }
        },
        {
          id: 'ghs-statements',
          name: 'Hazard Statements',
          type: 'text',
          x: 42,
          y: 28,
          width: 59,
          height: 20,
          rotation: 0,
          locked: false,
          visible: true,
          opacity: 1,
          zIndex: 7,
          text: '{{Hazard_Statements}}',
          style: { fontFamily: 'Segoe UI', fontSize: 6.5, fontWeight: '500', color: '#1e293b', alignment: 'left', wrap: true }
        },
        {
          id: 'ghs-barcode',
          name: 'Batch Tracking Barcode',
          type: 'barcode',
          x: 4,
          y: 50,
          width: 97,
          height: 20,
          rotation: 0,
          locked: false,
          visible: true,
          opacity: 1,
          zIndex: 8,
          value: '{{Batch_Barcode}}',
          barcodeStyle: {
            symbology: 'code128',
            humanReadable: true,
            humanReadableFont: 'monospace',
            humanReadableSize: 7.5,
            humanReadablePosition: 'bottom',
            moduleWidth: 0.35,
            quietZone: true,
            quietZoneSize: 2,
            color: '#000000',
            backgroundColor: '#ffffff'
          }
        }
      ]
    }
  },

  // 5. QR Smart Asset Tracking Tag
  {
    id: 'tpl-qr-asset-tracking',
    name: 'QR Smart Asset Tracking Tag & Property Mark',
    description: 'Durable hardware asset management tag featuring dual enterprise QR web resolver URL, serial number, and property demarcation.',
    category: 'asset',
    industry: 'Enterprise IT & Facilities',
    tags: ['Asset', 'QR Code', 'IT Hardware', 'Inventory', 'Facilities'],
    isBuiltin: true,
    isFavorite: true,
    created: '2026-09-05T08:00:00Z',
    modified: '2026-09-16T16:45:00Z',
    author: 'Enterprise Facilities Directorate',
    version: 1,
    isReadOnly: true,
    primarySymbology: 'qr',
    supportsQr: true,
    elementCount: 7,
    usageCount: 119,
    variables: [
      { key: 'Org_Name', label: 'Company / Organization Name', type: 'text', defaultValue: 'PROPERTY OF GLOBAL AEROSPACE CORP', sampleValue: 'PROPERTY OF GLOBAL AEROSPACE CORP', required: true },
      { key: 'Asset_Tag_ID', label: 'Asset Tag Number', type: 'text', defaultValue: 'AST-2026-09412', sampleValue: 'AST-2026-09412', required: true },
      { key: 'Asset_Category', label: 'Asset Category / Department', type: 'text', defaultValue: 'ENGINEERING LAB WORKSTATION', sampleValue: 'ENGINEERING LAB WORKSTATION' },
      { key: 'Asset_URL', label: 'Asset Portal Resolver URL', type: 'barcode', defaultValue: 'https://assets.corp.internal/view/AST-2026-09412', sampleValue: 'https://assets.corp.internal/view/AST-2026-09412', required: true }
    ],
    sampleData: {
      Org_Name: 'PROPERTY OF GLOBAL AEROSPACE CORP',
      Asset_Tag_ID: 'AST-2026-09412',
      Asset_Category: 'ENGINEERING LAB WORKSTATION',
      Asset_URL: 'https://assets.corp.internal/view/AST-2026-09412'
    },
    document: {
      id: 'tpl-qr-asset-tracking',
      schemaVersion: '1.0.0',
      name: 'QR Smart Asset Tracking Tag & Property Mark',
      description: 'Durable hardware asset management tag featuring dual enterprise QR web resolver URL, serial number, and property demarcation.',
      author: 'Enterprise Facilities Directorate',
      created: '2026-09-05T08:00:00Z',
      modified: '2026-09-16T16:45:00Z',
      dimensions: {
        width: 60,
        height: 30,
        unit: 'mm',
        dpi: 300,
        orientation: 'landscape',
        marginLeft: 1.5,
        marginTop: 1.5,
        marginRight: 1.5,
        marginBottom: 1.5,
        cornerRadius: 1.5
      },
      metadata: { targetPrinter: 'prn-02', site: 'HQ Engineering Lab', version: 1, status: 'approved' },
      objects: [
        {
          id: 'asset-hdr-bar',
          name: 'Property Header Banner',
          type: 'rect',
          x: 2,
          y: 2,
          width: 56,
          height: 6,
          rotation: 0,
          locked: true,
          visible: true,
          opacity: 1,
          zIndex: 1,
          shapeStyle: { fillColor: '#0f172a', strokeColor: '#000000', strokeWidth: 0.4 }
        },
        {
          id: 'asset-org-title',
          name: 'Organization Title',
          type: 'text',
          x: 3,
          y: 3,
          width: 54,
          height: 4,
          rotation: 0,
          locked: true,
          visible: true,
          opacity: 1,
          zIndex: 2,
          text: '{{Org_Name}}',
          style: { fontFamily: 'Segoe UI', fontSize: 6.5, fontWeight: 'bold', color: '#ffffff', alignment: 'center' }
        },
        {
          id: 'asset-qr',
          name: 'Asset Resolver QR Code',
          type: 'qrcode',
          x: 3,
          y: 9.5,
          width: 18,
          height: 18,
          rotation: 0,
          locked: false,
          visible: true,
          opacity: 1,
          zIndex: 3,
          value: '{{Asset_URL}}',
          barcodeStyle: {
            symbology: 'qr',
            humanReadable: false,
            humanReadableFont: 'monospace',
            humanReadableSize: 8,
            humanReadablePosition: 'none',
            moduleWidth: 0.35,
            quietZone: true,
            quietZoneSize: 1,
            color: '#000000',
            backgroundColor: '#ffffff'
          }
        },
        {
          id: 'asset-id-label',
          name: 'Asset Tag ID Label',
          type: 'text',
          x: 23,
          y: 10,
          width: 35,
          height: 7,
          rotation: 0,
          locked: false,
          visible: true,
          opacity: 1,
          zIndex: 4,
          text: '{{Asset_Tag_ID}}',
          style: { fontFamily: 'IBM Plex Mono', fontSize: 10, fontWeight: 'bold', color: '#0f172a', alignment: 'left' }
        },
        {
          id: 'asset-cat-text',
          name: 'Category Specification',
          type: 'text',
          x: 23,
          y: 18,
          width: 35,
          height: 5,
          rotation: 0,
          locked: false,
          visible: true,
          opacity: 1,
          zIndex: 5,
          text: '{{Asset_Category}}',
          style: { fontFamily: 'Segoe UI', fontSize: 6, fontWeight: '600', color: '#475569', alignment: 'left' }
        },
        {
          id: 'asset-warn-text',
          name: 'Security Tamper Notice',
          type: 'text',
          x: 23,
          y: 23,
          width: 35,
          height: 4,
          rotation: 0,
          locked: true,
          visible: true,
          opacity: 1,
          zIndex: 6,
          text: 'DO NOT REMOVE | TAMPER EVIDENT',
          style: { fontFamily: 'Segoe UI', fontSize: 5, fontWeight: 'bold', color: '#dc2626', alignment: 'left' }
        }
      ]
    }
  },

  // 6. Automotive Kanban AIAG B-10 Card
  {
    id: 'tpl-kanban-automotive',
    name: 'Automotive Kanban AIAG B-10 Parts Container Card',
    description: 'AIAG standard B-10 compliant automotive supply chain parts container card with PDF417 2D shipping manifest and Code 39 part identifiers.',
    category: 'manufacturing',
    industry: 'Automotive & Industrial Manufacturing',
    tags: ['Automotive', 'AIAG', 'Kanban', 'PDF417', 'Code 39', 'Manufacturing'],
    isBuiltin: true,
    isFavorite: false,
    created: '2026-09-06T08:00:00Z',
    modified: '2026-09-14T11:00:00Z',
    author: 'Automotive Supply Chain Taskforce',
    version: 1,
    isReadOnly: true,
    primarySymbology: 'pdf417',
    supportsQr: false,
    elementCount: 9,
    usageCount: 53,
    variables: [
      { key: 'Part_Number', label: 'OEM Part Number', type: 'text', defaultValue: 'PART (P): 4L84-9F593-AB', sampleValue: 'PART (P): 4L84-9F593-AB', required: true },
      { key: 'Part_Barcode', label: 'Part Number Barcode (Code 39)', type: 'barcode', defaultValue: 'P4L84-9F593-AB', sampleValue: 'P4L84-9F593-AB', required: true },
      { key: 'Container_Qty', label: 'Quantity per Bin', type: 'text', defaultValue: 'QTY (Q): 200 EA', sampleValue: 'QTY (Q): 200 EA', required: true },
      { key: 'Supplier_Code', label: 'DUNS / Supplier Code', type: 'text', defaultValue: 'SUPP (V): 048192041', sampleValue: 'SUPP (V): 048192041', required: true },
      { key: 'Plant_Loc', label: 'Delivery Dock / Line Feed Location', type: 'text', defaultValue: 'LINE 4 - CELL 12B', sampleValue: 'LINE 4 - CELL 12B' }
    ],
    sampleData: {
      Part_Number: 'PART (P): 4L84-9F593-AB',
      Part_Barcode: 'P4L84-9F593-AB',
      Container_Qty: 'QTY (Q): 200 EA',
      Supplier_Code: 'SUPP (V): 048192041',
      Plant_Loc: 'LINE 4 - CELL 12B'
    },
    document: {
      id: 'tpl-kanban-automotive',
      schemaVersion: '1.0.0',
      name: 'Automotive Kanban AIAG B-10 Parts Container Card',
      description: 'AIAG standard B-10 compliant automotive supply chain parts container card with PDF417 2D shipping manifest and Code 39 part identifiers.',
      author: 'Automotive Supply Chain Taskforce',
      created: '2026-09-06T08:00:00Z',
      modified: '2026-09-14T11:00:00Z',
      dimensions: {
        width: 150,
        height: 100,
        unit: 'mm',
        dpi: 300,
        orientation: 'landscape',
        marginLeft: 2,
        marginTop: 2,
        marginRight: 2,
        marginBottom: 2,
        cornerRadius: 0
      },
      metadata: { targetPrinter: 'prn-01', site: 'Assembly Plant 1', version: 1, status: 'approved' },
      objects: [
        {
          id: 'kanban-part-title',
          name: 'Part Number Header',
          type: 'text',
          x: 5,
          y: 5,
          width: 90,
          height: 8,
          rotation: 0,
          locked: false,
          visible: true,
          opacity: 1,
          zIndex: 1,
          text: '{{Part_Number}}',
          style: { fontFamily: 'Segoe UI', fontSize: 13, fontWeight: 'bold', color: '#0f172a', alignment: 'left' }
        },
        {
          id: 'kanban-part-bc',
          name: 'Part Code 39 Barcode',
          type: 'barcode',
          x: 5,
          y: 14,
          width: 85,
          height: 28,
          rotation: 0,
          locked: false,
          visible: true,
          opacity: 1,
          zIndex: 2,
          value: '{{Part_Barcode}}',
          barcodeStyle: {
            symbology: 'code39',
            humanReadable: true,
            humanReadableFont: 'monospace',
            humanReadableSize: 8,
            humanReadablePosition: 'bottom',
            moduleWidth: 0.35,
            quietZone: true,
            quietZoneSize: 2,
            color: '#000000',
            backgroundColor: '#ffffff'
          }
        },
        {
          id: 'kanban-loc-box',
          name: 'Line Location Callout Box',
          type: 'rect',
          x: 95,
          y: 5,
          width: 50,
          height: 37,
          rotation: 0,
          locked: true,
          visible: true,
          opacity: 1,
          zIndex: 3,
          shapeStyle: { fillColor: '#f8fafc', strokeColor: '#0f172a', strokeWidth: 0.8, borderRadius: 1 }
        },
        {
          id: 'kanban-loc-title',
          name: 'Drop Point Header',
          type: 'text',
          x: 97,
          y: 8,
          width: 46,
          height: 5,
          rotation: 0,
          locked: true,
          visible: true,
          opacity: 1,
          zIndex: 4,
          text: 'LINE FEED TARGET:',
          style: { fontFamily: 'Segoe UI', fontSize: 7.5, fontWeight: 'bold', color: '#475569', alignment: 'center' }
        },
        {
          id: 'kanban-loc-val',
          name: 'Drop Point Value',
          type: 'text',
          x: 97,
          y: 17,
          width: 46,
          height: 16,
          rotation: 0,
          locked: false,
          visible: true,
          opacity: 1,
          zIndex: 5,
          text: '{{Plant_Loc}}',
          style: { fontFamily: 'Segoe UI', fontSize: 15, fontWeight: 'bold', color: '#0f172a', alignment: 'center', wrap: true }
        },
        {
          id: 'kanban-div',
          name: 'Horizontal Section Divider',
          type: 'line',
          x: 5,
          y: 45,
          width: 140,
          height: 0.5,
          rotation: 0,
          locked: true,
          visible: true,
          opacity: 1,
          zIndex: 6,
          shapeStyle: { fillColor: '#000000', strokeColor: '#000000', strokeWidth: 0.8 }
        },
        {
          id: 'kanban-qty-title',
          name: 'Quantity and Supplier Row',
          type: 'text',
          x: 5,
          y: 48,
          width: 140,
          height: 7,
          rotation: 0,
          locked: false,
          visible: true,
          opacity: 1,
          zIndex: 7,
          text: '{{Container_Qty}}   |   {{Supplier_Code}}',
          style: { fontFamily: 'IBM Plex Mono', fontSize: 10, fontWeight: 'bold', color: '#0f172a', alignment: 'left' }
        },
        {
          id: 'kanban-pdf417',
          name: 'AIAG 2D PDF417 Manifest Barcode',
          type: 'barcode',
          x: 5,
          y: 57,
          width: 140,
          height: 38,
          rotation: 0,
          locked: false,
          visible: true,
          opacity: 1,
          zIndex: 8,
          value: '[)>*06*12S048192041*P4L84-9F593-AB*Q200*1T2026090601',
          barcodeStyle: {
            symbology: 'pdf417',
            humanReadable: true,
            humanReadableFont: 'monospace',
            humanReadableSize: 7,
            humanReadablePosition: 'bottom',
            moduleWidth: 0.35,
            quietZone: true,
            quietZoneSize: 2,
            color: '#000000',
            backgroundColor: '#ffffff'
          }
        }
      ]
    }
  },

  // 7. Warehouse Bin & Pallet Racking Location
  {
    id: 'tpl-warehouse-bin-rack',
    name: 'Warehouse Bin & Pallet Racking Location Sign',
    description: 'High-visibility warehouse aisle and racking location placard with large human-readable zone codes and Code 128 scan target.',
    category: 'warehouse',
    industry: 'Fulfillment & Distribution',
    tags: ['Warehouse', 'Racking', 'Bin Location', 'Aisle', 'Code 128', 'WMS'],
    isBuiltin: true,
    isFavorite: false,
    created: '2026-09-04T08:00:00Z',
    modified: '2026-09-13T12:00:00Z',
    author: 'Warehouse Infrastructure Logistics',
    version: 1,
    isReadOnly: true,
    primarySymbology: 'code128',
    supportsQr: false,
    elementCount: 6,
    usageCount: 71,
    variables: [
      { key: 'Aisle_Zone', label: 'Aisle Zone Header', type: 'text', defaultValue: 'ZONE 04 - AISLE 12', sampleValue: 'ZONE 04 - AISLE 12', required: true },
      { key: 'Bin_Location', label: 'Full Bin Identifier (Section-Bay-Level)', type: 'text', defaultValue: '04-12-08-C', sampleValue: '04-12-08-C', required: true },
      { key: 'Bin_Barcode', label: 'WMS Scan Barcode Value', type: 'barcode', defaultValue: 'LOC-041208C', sampleValue: 'LOC-041208C', required: true }
    ],
    sampleData: {
      Aisle_Zone: 'ZONE 04 - AISLE 12',
      Bin_Location: '04-12-08-C',
      Bin_Barcode: 'LOC-041208C'
    },
    document: {
      id: 'tpl-warehouse-bin-rack',
      schemaVersion: '1.0.0',
      name: 'Warehouse Bin & Pallet Racking Location Sign',
      description: 'High-visibility warehouse aisle and racking location placard with large human-readable zone codes and Code 128 scan target.',
      author: 'Warehouse Infrastructure Logistics',
      created: '2026-09-04T08:00:00Z',
      modified: '2026-09-13T12:00:00Z',
      dimensions: {
        width: 100,
        height: 40,
        unit: 'mm',
        dpi: 300,
        orientation: 'landscape',
        marginLeft: 2,
        marginTop: 2,
        marginRight: 2,
        marginBottom: 2,
        cornerRadius: 0
      },
      metadata: { targetPrinter: 'prn-01', site: 'Warehouse Bay 4', version: 1, status: 'approved' },
      objects: [
        {
          id: 'rack-zone-hdr',
          name: 'Aisle Zone Header',
          type: 'text',
          x: 3,
          y: 3,
          width: 94,
          height: 5,
          rotation: 0,
          locked: false,
          visible: true,
          opacity: 1,
          zIndex: 1,
          text: '{{Aisle_Zone}}',
          style: { fontFamily: 'Segoe UI', fontSize: 8, fontWeight: 'bold', color: '#475569', alignment: 'center' }
        },
        {
          id: 'rack-bin-val',
          name: 'Big Bin Location Number',
          type: 'text',
          x: 3,
          y: 7,
          width: 94,
          height: 14,
          rotation: 0,
          locked: false,
          visible: true,
          opacity: 1,
          zIndex: 2,
          text: '{{Bin_Location}}',
          style: { fontFamily: 'Segoe UI', fontSize: 18, fontWeight: 'bold', color: '#000000', alignment: 'center' }
        },
        {
          id: 'rack-barcode',
          name: 'WMS Code 128 Scan Barcode',
          type: 'barcode',
          x: 5,
          y: 21,
          width: 90,
          height: 16,
          rotation: 0,
          locked: false,
          visible: true,
          opacity: 1,
          zIndex: 3,
          value: '{{Bin_Barcode}}',
          barcodeStyle: {
            symbology: 'code128',
            humanReadable: false,
            humanReadableFont: 'monospace',
            humanReadableSize: 8,
            humanReadablePosition: 'none',
            moduleWidth: 0.4,
            quietZone: true,
            quietZoneSize: 2,
            color: '#000000',
            backgroundColor: '#ffffff'
          }
        }
      ]
    }
  },

  // 8. Master Carton Packaging Mark (ITF-14)
  {
    id: 'tpl-carton-itf14',
    name: 'Master Carton Packaging Mark (ITF-14)',
    description: 'Corrugated master carton dispatch label featuring high-tolerance ITF-14 bearer bar barcode for warehouse sorting.',
    category: 'packaging',
    industry: 'Packaging & FMCG',
    tags: ['ITF-14', 'Master Carton', 'Corrugated', 'Packaging', 'GS1'],
    isBuiltin: true,
    isFavorite: false,
    created: '2026-09-04T08:00:00Z',
    modified: '2026-09-14T11:00:00Z',
    author: 'Packaging Quality Assurance',
    version: 1,
    isReadOnly: true,
    primarySymbology: 'itf14',
    supportsQr: false,
    elementCount: 5,
    usageCount: 37,
    variables: [
      { key: 'Carton_Desc', label: 'Carton Description', type: 'text', defaultValue: 'INDUSTRIAL SENSOR MODULES (PACK OF 24)', sampleValue: 'INDUSTRIAL SENSOR MODULES (PACK OF 24)', required: true },
      { key: 'Case_Qty', label: 'Case Pack Quantity', type: 'text', defaultValue: 'QTY: 24 UNITS | NET: 4.8 KG | GROSS: 5.6 KG', sampleValue: 'QTY: 24 UNITS | NET: 4.8 KG | GROSS: 5.6 KG' },
      { key: 'ITF_Code', label: '14-Digit ITF-14 Barcode', type: 'barcode', defaultValue: '10012345678902', sampleValue: '10012345678902', required: true }
    ],
    sampleData: {
      Carton_Desc: 'INDUSTRIAL SENSOR MODULES (PACK OF 24)',
      Case_Qty: 'QTY: 24 UNITS | NET: 4.8 KG | GROSS: 5.6 KG',
      ITF_Code: '10012345678902'
    },
    document: {
      id: 'tpl-carton-itf14',
      schemaVersion: '1.0.0',
      name: 'Master Carton Packaging Mark (ITF-14)',
      description: 'Corrugated master carton dispatch label featuring high-tolerance ITF-14 bearer bar barcode.',
      author: 'Packaging Quality Assurance',
      created: '2026-09-04T08:00:00Z',
      modified: '2026-09-14T11:00:00Z',
      dimensions: {
        width: 100,
        height: 50,
        unit: 'mm',
        dpi: 300,
        orientation: 'landscape',
        marginLeft: 2,
        marginTop: 2,
        marginRight: 2,
        marginBottom: 2,
        cornerRadius: 0
      },
      metadata: { targetPrinter: 'prn-01', site: 'Packing Station Alpha', version: 1, status: 'approved' },
      objects: [
        {
          id: 'itf-carton-title',
          name: 'Carton Content Title',
          type: 'text',
          x: 4,
          y: 3,
          width: 92,
          height: 6,
          rotation: 0,
          locked: false,
          visible: true,
          opacity: 1,
          zIndex: 1,
          text: '{{Carton_Desc}}',
          style: { fontFamily: 'Segoe UI', fontSize: 8.5, fontWeight: 'bold', color: '#000000', alignment: 'left' }
        },
        {
          id: 'itf-carton-qty',
          name: 'Case Quantity & Weights',
          type: 'text',
          x: 4,
          y: 10,
          width: 92,
          height: 5,
          rotation: 0,
          locked: false,
          visible: true,
          opacity: 1,
          zIndex: 2,
          text: '{{Case_Qty}}',
          style: { fontFamily: 'IBM Plex Mono', fontSize: 7, fontWeight: 'bold', color: '#334155', alignment: 'left' }
        },
        {
          id: 'itf-14-barcode',
          name: 'ITF-14 Shipping Barcode with Bearer Bars',
          type: 'barcode',
          x: 5,
          y: 17,
          width: 90,
          height: 30,
          rotation: 0,
          locked: false,
          visible: true,
          opacity: 1,
          zIndex: 3,
          value: '{{ITF_Code}}',
          barcodeStyle: {
            symbology: 'itf14',
            humanReadable: true,
            humanReadableFont: 'monospace',
            humanReadableSize: 8.5,
            humanReadablePosition: 'bottom',
            moduleWidth: 0.45,
            quietZone: true,
            quietZoneSize: 3,
            bearerBars: true,
            color: '#000000',
            backgroundColor: '#ffffff'
          }
        }
      ]
    }
  }
];

export const BUILTIN_TEMPLATES = BUILTIN_TEMPLATE_LIBRARY;

export const STANDARD_LABEL_PRESETS: LabelSizePreset[] = [
  {
    id: 'preset-shipping-4x6',
    name: '4" x 6" Logistics Pallet (100 x 150 mm)',
    category: 'shipping',
    width: 100,
    height: 150,
    unit: 'mm',
    description: 'Standard carrier freight and GS1 pallet specification.',
    commonUse: 'FedEx, UPS, DHL, GS1-128 Logistics Shipping',
  },
  {
    id: 'preset-shipping-4x4',
    name: '4" x 4" Square Carton (100 x 100 mm)',
    category: 'shipping',
    width: 100,
    height: 100,
    unit: 'mm',
    description: 'Square logistics box and freight routing mark.',
    commonUse: 'Distribution Center Cross-docking',
  },
  {
    id: 'preset-retail-hangtag',
    name: '2" x 3.5" Retail Hang Tag (50 x 90 mm)',
    category: 'retail',
    width: 50,
    height: 90,
    unit: 'mm',
    description: 'Garment hang tag with EAN/UPC POS barcode.',
    commonUse: 'Apparel, Footwear, Fashion Accessories',
  },
  {
    id: 'preset-medical-udi',
    name: '3.15" x 1.77" FDA UDI Device (80 x 45 mm)',
    category: 'healthcare',
    width: 80,
    height: 45,
    unit: 'mm',
    description: 'FDA & EU MDR sterile medical packaging.',
    commonUse: 'Vials, Catheters, Implant Sterile Trays',
  },
  {
    id: 'preset-asset-compact',
    name: '2.36" x 1.18" Asset Metal Tag (60 x 30 mm)',
    category: 'asset',
    width: 60,
    height: 30,
    unit: 'mm',
    description: 'High-durability hardware asset badge with QR code.',
    commonUse: 'Laptops, Server Racks, Lab Equipment',
  },
  {
    id: 'preset-warehouse-rack',
    name: '4" x 1.6" Warehouse Bin Location (100 x 40 mm)',
    category: 'warehouse',
    width: 100,
    height: 40,
    unit: 'mm',
    description: 'Pallet racking beam and pick-face label.',
    commonUse: 'WMS Warehouse Bin & Aisle Signs',
  },
  {
    id: 'preset-ghs-placard',
    name: '4.13" x 2.9" GHS Chemical Drum (105 x 74 mm)',
    category: 'warning',
    width: 105,
    height: 74,
    unit: 'mm',
    description: 'OSHA / GHS standardized chemical container notice.',
    commonUse: 'Solvent Drums, Hazmat Secondary Vessels',
  },
  {
    id: 'preset-itf14-carton',
    name: '4" x 2" Master Carton (100 x 50 mm)',
    category: 'packaging',
    width: 100,
    height: 50,
    unit: 'mm',
    description: 'Corrugated master outer packaging with ITF-14 barcode.',
    commonUse: 'Corrugated Outer Cases & Shipper Boxes',
  },
];

