/**
 * LabelForge TSPL (TSC Printer Language) & EPL Code Generators
 */

import { LabelDocument, TextLabelObject, BarcodeLabelObject, ShapeLabelObject } from '../types/label';
import { mmToDots } from './zplGenerator';

export function generateTsplFromDocument(doc: LabelDocument, options?: { copies?: number; darkness?: number; speed?: number }): string {
  const dpi = doc.dimensions.dpi || 300;
  const copies = options?.copies || 1;
  const darkness = options?.darkness !== undefined ? options.darkness : 10;
  const speed = options?.speed || 4;

  const lines: string[] = [
    `SIZE ${doc.dimensions.width} mm, ${doc.dimensions.height} mm`,
    'GAP 3 mm, 0 mm',
    `SPEED ${speed}`,
    `DENSITY ${darkness}`,
    'DIRECTION 1',
    'REFERENCE 0,0',
    'CLS',
    `; Generated by LabelForge Studio: ${doc.name}`,
  ];

  const sortedObjects = [...doc.objects].sort((a, b) => a.zIndex - b.zIndex);

  for (const obj of sortedObjects) {
    if (!obj.visible) continue;
    const xDots = mmToDots(obj.x, dpi);
    const yDots = mmToDots(obj.y, dpi);
    const wDots = mmToDots(obj.width, dpi);
    const hDots = mmToDots(obj.height, dpi);

    if (obj.type === 'text' || obj.type === 'rich-text') {
      const textObj = obj as TextLabelObject;
      const fontHeight = Math.max(1, Math.round(textObj.style.fontSize / 10));
      lines.push(`TEXT ${xDots},${yDots},"3",0,${fontHeight},${fontHeight},"${textObj.text.replace(/"/g, '\\"')}"`);
    } else if (obj.type === 'barcode' || obj.type === 'qrcode' || obj.type === 'datamatrix') {
      const bObj = obj as BarcodeLabelObject;
      const hr = bObj.barcodeStyle.humanReadable ? 1 : 0;
      if (bObj.barcodeStyle.symbology === 'qr' || bObj.barcodeStyle.symbology === 'gs1-qr') {
        lines.push(`QRCODE ${xDots},${yDots},M,4,A,0,"${bObj.value.replace(/"/g, '\\"')}"`);
      } else if (bObj.barcodeStyle.symbology === 'datamatrix' || bObj.barcodeStyle.symbology === 'gs1-datamatrix') {
        lines.push(`DMATRIX ${xDots},${yDots},${wDots},${hDots},"${bObj.value.replace(/"/g, '\\"')}"`);
      } else {
        lines.push(`BARCODE ${xDots},${yDots},"128",${hDots},${hr},0,2,4,"${bObj.value}"`);
      }
    } else if (obj.type === 'rect') {
      const shape = obj as ShapeLabelObject;
      const border = Math.max(1, mmToDots(shape.shapeStyle.strokeWidth || 0.3, dpi));
      lines.push(`BOX ${xDots},${yDots},${xDots + wDots},${yDots + hDots},${border}`);
    } else if (obj.type === 'line') {
      const shape = obj as ShapeLabelObject;
      const border = Math.max(1, mmToDots(shape.shapeStyle.strokeWidth || 0.3, dpi));
      lines.push(`BAR ${xDots},${yDots},${wDots},${border}`);
    }
  }

  lines.push(`PRINT ${copies},1`);
  return lines.join('\n');
}

export function generateEplFromDocument(doc: LabelDocument, options?: { copies?: number; darkness?: number; speed?: number }): string {
  const dpi = doc.dimensions.dpi || 203; // EPL usually 203 DPI
  const copies = options?.copies || 1;
  const darkness = options?.darkness !== undefined ? options.darkness : 8;
  const speed = options?.speed || 3;

  const lines: string[] = [
    'N', // Clear image buffer
    `D${darkness}`, // Density
    `S${speed}`, // Speed
    `q${mmToDots(doc.dimensions.width, dpi)}`, // Label width
    `Q${mmToDots(doc.dimensions.height, dpi)},24`, // Label length and gap
    `; EPL output generated by LabelForge Studio: ${doc.name}`,
  ];

  const sortedObjects = [...doc.objects].sort((a, b) => a.zIndex - b.zIndex);

  for (const obj of sortedObjects) {
    if (!obj.visible) continue;
    const x = mmToDots(obj.x, dpi);
    const y = mmToDots(obj.y, dpi);

    if (obj.type === 'text' || obj.type === 'rich-text') {
      const textObj = obj as TextLabelObject;
      lines.push(`A${x},${y},0,4,1,1,N,"${textObj.text.replace(/"/g, '\\"')}"`);
    } else if (obj.type === 'barcode') {
      const bObj = obj as BarcodeLabelObject;
      const h = mmToDots(obj.height, dpi);
      lines.push(`B${x},${y},0,1,2,4,${h},B,"${bObj.value}"`);
    }
  }

  lines.push(`P${copies}`);
  return lines.join('\n');
}
