/**
 * LabelForge ZPL-II (Zebra Programming Language) Code Generator
 * Compiles canonical LabelDocument into authentic ZPL commands for thermal printers
 */

import { LabelDocument, LabelObject, TextLabelObject, BarcodeLabelObject, ShapeLabelObject } from '../types/label';

export function mmToDots(mm: number, dpi: number): number {
  return Math.round((mm * dpi) / 25.4);
}

export function generateZplFromDocument(doc: LabelDocument, options?: { copies?: number; darkness?: number; speed?: number }): string {
  const dpi = doc.dimensions.dpi || 300;
  const labelWidthDots = mmToDots(doc.dimensions.width, dpi);
  const labelLengthDots = mmToDots(doc.dimensions.height, dpi);
  const copies = options?.copies || 1;
  const darkness = options?.darkness !== undefined ? options.darkness : 15;
  const speed = options?.speed || 6;

  const lines: string[] = [
    'CT~~CD,~CC^~CT~',
    '^XA',
    `^PW${labelWidthDots}`,
    `^LL${labelLengthDots}`,
    '^LH0,0',
    `^PR${speed},${speed}`,
    `^MD${darkness}`,
    '^PON',
    '^CI28', // UTF-8 Unicode encoding in ZPL
    `^FX --- Generated by LabelForge Studio: ${doc.name} (v${doc.metadata.version || 1}) ---`,
  ];

  // Sort objects by zIndex
  const sortedObjects = [...doc.objects].sort((a, b) => a.zIndex - b.zIndex);

  for (const obj of sortedObjects) {
    if (!obj.visible) continue;

    const xDots = mmToDots(obj.x, dpi);
    const yDots = mmToDots(obj.y, dpi);
    const wDots = mmToDots(obj.width, dpi);
    const hDots = mmToDots(obj.height, dpi);

    lines.push(`^FX Object: ${obj.name} (${obj.type})`);
    lines.push(`^FO${xDots},${yDots}`);

    if (obj.type === 'text' || obj.type === 'rich-text') {
      const textObj = obj as TextLabelObject;
      const fontHeightDots = Math.max(15, Math.round(textObj.style.fontSize * (dpi / 72)));
      const fontWidthDots = Math.round(fontHeightDots * 0.75);
      
      // Select font or scalable Swiss 721
      lines.push(`^A0N,${fontHeightDots},${fontWidthDots}`);
      if (textObj.style.wrap) {
        lines.push(`^FB${wDots},5,0,${textObj.style.alignment === 'center' ? 'C' : textObj.style.alignment === 'right' ? 'R' : 'L'},0`);
      }
      lines.push(`^FD${textObj.text.replace(/\^/g, '_5E').replace(/~/g, '_7E')}^FS`);
    } else if (obj.type === 'barcode' || obj.type === 'qrcode' || obj.type === 'datamatrix') {
      const bObj = obj as BarcodeLabelObject;
      const symbology = bObj.barcodeStyle.symbology;
      const hrOption = bObj.barcodeStyle.humanReadable ? 'Y' : 'N';

      if (symbology === 'code128' || symbology === 'gs1-128') {
        // ^BCo,h,f,g,e,m (Code 128)
        lines.push(`^BY${Math.max(2, Math.round(wDots / 60))},3,${hDots}`);
        lines.push(`^BCN,${hDots},${hrOption},N,N`);
        lines.push(`^FD>;>${bObj.value}^FS`);
      } else if (symbology === 'code39') {
        // ^B3o,e,h,f,g
        lines.push(`^BY${Math.max(2, Math.round(wDots / 50))},2.5,${hDots}`);
        lines.push(`^B3N,N,${hDots},${hrOption},N`);
        lines.push(`^FD${bObj.value}^FS`);
      } else if (symbology === 'ean13') {
        lines.push(`^BY${Math.max(2, Math.round(wDots / 45))},3,${hDots}`);
        lines.push(`^BEN,${hDots},${hrOption},N`);
        lines.push(`^FD${bObj.value}^FS`);
      } else if (symbology === 'upca') {
        lines.push(`^BY${Math.max(2, Math.round(wDots / 45))},3,${hDots}`);
        lines.push(`^BUN,${hDots},${hrOption},N,Y`);
        lines.push(`^FD${bObj.value}^FS`);
      } else if (symbology === 'qr' || symbology === 'gs1-qr') {
        // ^BQa,b,c,d,e (QR Code: model 2, magnification, ECC)
        const mag = Math.max(3, Math.min(10, Math.round(wDots / 35)));
        lines.push(`^BQN,2,${mag},M,7`);
        lines.push(`^FDQA,${bObj.value}^FS`);
      } else if (symbology === 'datamatrix' || symbology === 'gs1-datamatrix') {
        // ^BXo,h,s,c,r,f,g (Data Matrix)
        const dim = Math.max(4, Math.round(wDots / 20));
        lines.push(`^BXN,${dim},200`);
        lines.push(`^FD${bObj.value}^FS`);
      } else if (symbology === 'pdf417') {
        lines.push(`^BY2,3,${hDots}`);
        lines.push(`^B7N,${hDots},1,2,6,N`);
        lines.push(`^FD${bObj.value}^FS`);
      } else {
        // Fallback Code 128
        lines.push(`^BY2,3,${hDots}`);
        lines.push(`^BCN,${hDots},${hrOption},N,N`);
        lines.push(`^FD${bObj.value}^FS`);
      }
    } else if (obj.type === 'rect') {
      const shape = obj as ShapeLabelObject;
      const borderDots = Math.max(1, mmToDots(shape.shapeStyle.strokeWidth || 0.3, dpi));
      const cornerRounding = shape.shapeStyle.borderRadius ? Math.min(8, Math.round(shape.shapeStyle.borderRadius)) : 0;
      lines.push(`^GB${wDots},${hDots},${borderDots},B,${cornerRounding}^FS`);
    } else if (obj.type === 'line') {
      const shape = obj as ShapeLabelObject;
      const borderDots = Math.max(1, mmToDots(shape.shapeStyle.strokeWidth || 0.3, dpi));
      lines.push(`^GB${wDots},${borderDots},${borderDots}^FS`);
    }
  }

  // Print quantity
  lines.push(`^PQ${copies},0,1,Y`);
  lines.push('^XZ');

  return lines.join('\n');
}
